#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: _MENU_CheatConsole

#include "Basic.hpp"

#include "_MENU_CheatConsole_classes.hpp"
#include "_MENU_CheatConsole_parameters.hpp"


namespace SDK
{

// Function _MENU_CheatConsole._MENU_CheatConsole_C.OnKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FKeyEvent                        InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply U_MENU_CheatConsole_C::OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "OnKeyUp");

	Params::_MENU_CheatConsole_C_OnKeyUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.OnLoaded_5087EABD4CB81111640A91B2888B99F6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UObject>              Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void U_MENU_CheatConsole_C::OnLoaded_5087EABD4CB81111640A91B2888B99F6(TSubclassOf<class UObject> Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "OnLoaded_5087EABD4CB81111640A91B2888B99F6");

	Params::_MENU_CheatConsole_C_OnLoaded_5087EABD4CB81111640A91B2888B99F6 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void U_MENU_CheatConsole_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "PreConstruct");

	Params::_MENU_CheatConsole_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.OnShown
// (Event, Protected, BlueprintEvent)

void U_MENU_CheatConsole_C::OnShown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "OnShown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Button_XP_K2Node_ComponentBoundEvent_238_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Button_XP_K2Node_ComponentBoundEvent_238_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Button_XP_K2Node_ComponentBoundEvent_238_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Button_Credits_K2Node_ComponentBoundEvent_239_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Button_Credits_K2Node_ComponentBoundEvent_239_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Button_Credits_K2Node_ComponentBoundEvent_239_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Button_Resources_K2Node_ComponentBoundEvent_242_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Button_Resources_K2Node_ComponentBoundEvent_242_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Button_Resources_K2Node_ComponentBoundEvent_242_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Button_Perks_K2Node_ComponentBoundEvent_246_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Button_Perks_K2Node_ComponentBoundEvent_246_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Button_Perks_K2Node_ComponentBoundEvent_246_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_RotateMissions_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_RotateMissions_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_RotateMissions_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_Connect_K2Node_ComponentBoundEvent_54_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_Connect_K2Node_ComponentBoundEvent_54_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_Connect_K2Node_ComponentBoundEvent_54_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_UnlockAllWeapons_K2Node_ComponentBoundEvent_44_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_UnlockAllWeapons_K2Node_ComponentBoundEvent_44_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_UnlockAllWeapons_K2Node_ComponentBoundEvent_44_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_ResetUpgrades_K2Node_ComponentBoundEvent_58_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_ResetUpgrades_K2Node_ComponentBoundEvent_58_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_ResetUpgrades_K2Node_ComponentBoundEvent_58_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_AdvanceCampaign_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_AdvanceCampaign_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_AdvanceCampaign_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_UnlockAllUpgrades_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_UnlockAllUpgrades_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_UnlockAllUpgrades_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_GiveSchematics_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_GiveSchematics_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_GiveSchematics_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_ForgeSchematics_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_ForgeSchematics_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_ForgeSchematics_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_ResetSchematics_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_ResetSchematics_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_ResetSchematics_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_GiveRandomSchematic_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_GiveRandomSchematic_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_GiveRandomSchematic_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_ForceCrates_K2Node_ComponentBoundEvent_6_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_ForceCrates_K2Node_ComponentBoundEvent_6_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_ForceCrates_K2Node_ComponentBoundEvent_6_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_StartMission_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_StartMission_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_StartMission_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.Back Pressed
// (BlueprintCallable, BlueprintEvent)

void U_MENU_CheatConsole_C::Back_Pressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "Back Pressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_GivePickaxeVanity_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_GivePickaxeVanity_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_GivePickaxeVanity_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_ResetPickaxeVanity_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_ResetPickaxeVanity_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_ResetPickaxeVanity_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_ForceLostPack_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_ForceLostPack_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_ForceLostPack_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_ShowAllCreatures_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_ShowAllCreatures_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_ShowAllCreatures_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_RotateDeepDive_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_RotateDeepDive_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_RotateDeepDive_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Basic_CompleteCampaign_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Basic_CompleteCampaign_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Basic_CompleteCampaign_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt__Button_CustomMission_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt__Button_CustomMission_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt__Button_CustomMission_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt___MENU_CheatConsole_Basic_RotateMissionOnce_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt___MENU_CheatConsole_Basic_RotateMissionOnce_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt___MENU_CheatConsole_Basic_RotateMissionOnce_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt___MENU_CheatConsole_Basic_GiveSeasonXP_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt___MENU_CheatConsole_Basic_GiveSeasonXP_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt___MENU_CheatConsole_Basic_GiveSeasonXP_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt___MENU_CheatConsole_Basic_AddSeasonLevel_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt___MENU_CheatConsole_Basic_AddSeasonLevel_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt___MENU_CheatConsole_Basic_AddSeasonLevel_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.BndEvt___MENU_CheatConsole_Basic_ResetSeasonXP_K2Node_ComponentBoundEvent_19_OnClicked__DelegateSignature
// (BlueprintEvent)

void U_MENU_CheatConsole_C::BndEvt___MENU_CheatConsole_Basic_ResetSeasonXP_K2Node_ComponentBoundEvent_19_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "BndEvt___MENU_CheatConsole_Basic_ResetSeasonXP_K2Node_ComponentBoundEvent_19_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function _MENU_CheatConsole._MENU_CheatConsole_C.ExecuteUbergraph__MENU_CheatConsole
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void U_MENU_CheatConsole_C::ExecuteUbergraph__MENU_CheatConsole(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("_MENU_CheatConsole_C", "ExecuteUbergraph__MENU_CheatConsole");

	Params::_MENU_CheatConsole_C_ExecuteUbergraph__MENU_CheatConsole Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

