#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Bosco

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "FSD_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Bosco.ABP_Bosco_C
// 0x1ED0 (0x21C0 - 0x02F0)
class UABP_Bosco_C final : public UBoscoAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02F8(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x0328(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x0350(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x0378(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x03A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x03C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x03F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x0418(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x0440(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x0468(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x0490(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x04B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x04E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x0508(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x0530(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x0558(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x0580(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x05A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x05D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x05F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x0620(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x0648(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x0670(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x0698(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x06C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x06E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x0710(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x0738(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x0760(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x0788(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x07B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x07D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x0800(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x0828(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x0850(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x0878(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_21;                   // 0x08A0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x0920(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_20;                   // 0x0950(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x09D0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_19;                   // 0x0A00(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x0A80(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_18;                   // 0x0AB0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x0B30(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17;                   // 0x0B60(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x0BE0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x0C10(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x0C90(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x0CC0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x0D40(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x0D70(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x0DF0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x0E20(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x0EA0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x0ED0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x0F50(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x0F80(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x1000(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x1030(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x10B0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x10E0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x1160(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x1190(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x1210(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x1240(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x12C0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x12F0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x1370(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x13A0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x1420(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x1450(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x14D0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x1500(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x1580(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x15B0(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x1630(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x1660(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x16E0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x1710(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x1790(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x17C0(0x00B0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2;                              // 0x1870(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x18B8(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x1900(0x0048)()
	uint8                                         Pad_54AB[0x8];                                     // 0x1948(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody;                           // 0x1950(0x0830)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x2180(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x21A0(0x0020)()

public:
	void AnimGraph(struct FPoseLink* Param_AnimGraph);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_2C87CB004D2625203839959DD2898B0F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_E97316F74C131834F52E939615D6EB9F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_7C2E57174982EB80CAE0FF84E27EBCBF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_D183605245E4CB43E6534A9BA6BACB3B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_DEE9FCD1470CCB102ED91EA81D4E7E1E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_4210E8D0438F626F0E4D59B0905F0238();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_0D42714B4E07EE59C224B6AA5BA921EE();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_CBBCF4F5412015C64C234F81CB72BB53();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_41E16860408AC6C966BA7293316AABA7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_E393F0194FCE38452A8905B4D30BB79F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_8551AEFD41DECDD1552AA7967752B2A9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_AC6E7F4141767F676AB4B7ABB9BCF08B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_AE7C675B491AD99BA560EF80DF56A191();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_B234EC8445E906CA1BB3FEA4CF754B26();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_17AED0154078A27DA892FB904C2082E8();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Bosco_AnimGraphNode_TransitionResult_A12C4F58420253460CD31B87CE6C378A();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void BlueprintInitializeAnimation();
	void ExecuteUbergraph_ABP_Bosco(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_Bosco_C">();
	}
	static class UABP_Bosco_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Bosco_C>();
	}
};
static_assert(alignof(UABP_Bosco_C) == 0x000010, "Wrong alignment on UABP_Bosco_C");
static_assert(sizeof(UABP_Bosco_C) == 0x0021C0, "Wrong size on UABP_Bosco_C");
static_assert(offsetof(UABP_Bosco_C, UberGraphFrame) == 0x0002F0, "Member 'UABP_Bosco_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_Root) == 0x0002F8, "Member 'UABP_Bosco_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_34) == 0x000328, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_34' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_33) == 0x000350, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_33' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_32) == 0x000378, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_32' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_31) == 0x0003A0, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_31' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_30) == 0x0003C8, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_30' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_29) == 0x0003F0, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_29' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_28) == 0x000418, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_28' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_27) == 0x000440, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_27' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_26) == 0x000468, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_26' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_25) == 0x000490, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_25' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_24) == 0x0004B8, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_24' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_23) == 0x0004E0, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_23' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_22) == 0x000508, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_22' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_21) == 0x000530, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_21' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_20) == 0x000558, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_20' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_19) == 0x000580, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_19' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_18) == 0x0005A8, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_18' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_17) == 0x0005D0, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_17' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_16) == 0x0005F8, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_16' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_15) == 0x000620, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_15' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_14) == 0x000648, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_14' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_13) == 0x000670, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_13' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_12) == 0x000698, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_11) == 0x0006C0, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_10) == 0x0006E8, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_9) == 0x000710, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_8) == 0x000738, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_7) == 0x000760, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_6) == 0x000788, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_5) == 0x0007B0, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_4) == 0x0007D8, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_3) == 0x000800, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_2) == 0x000828, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult_1) == 0x000850, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_TransitionResult) == 0x000878, "Member 'UABP_Bosco_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_21) == 0x0008A0, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_21' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_21) == 0x000920, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_21' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_20) == 0x000950, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_20' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_20) == 0x0009D0, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_20' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_19) == 0x000A00, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_19' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_19) == 0x000A80, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_19' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_18) == 0x000AB0, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_18' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_18) == 0x000B30, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_18' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_17) == 0x000B60, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_17' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_17) == 0x000BE0, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_17' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_16) == 0x000C10, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_16' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_16) == 0x000C90, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_16' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_15) == 0x000CC0, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_15' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_15) == 0x000D40, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_15' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_14) == 0x000D70, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_14' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_14) == 0x000DF0, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_14' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_13) == 0x000E20, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_13' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_13) == 0x000EA0, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_13' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_12) == 0x000ED0, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_12) == 0x000F50, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_12' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_11) == 0x000F80, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_11) == 0x001000, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_11' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_10) == 0x001030, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_10) == 0x0010B0, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_10' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_9) == 0x0010E0, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_9) == 0x001160, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_9' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_8) == 0x001190, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_8) == 0x001210, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_8' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_7) == 0x001240, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_7) == 0x0012C0, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_7' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_6) == 0x0012F0, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_6) == 0x001370, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_5) == 0x0013A0, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_5) == 0x001420, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_4) == 0x001450, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_4) == 0x0014D0, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_3) == 0x001500, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_3) == 0x001580, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_2) == 0x0015B0, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_2) == 0x001630, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer_1) == 0x001660, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult_1) == 0x0016E0, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_SequencePlayer) == 0x001710, "Member 'UABP_Bosco_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateResult) == 0x001790, "Member 'UABP_Bosco_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_StateMachine) == 0x0017C0, "Member 'UABP_Bosco_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_Slot_2) == 0x001870, "Member 'UABP_Bosco_C::AnimGraphNode_Slot_2' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_Slot_1) == 0x0018B8, "Member 'UABP_Bosco_C::AnimGraphNode_Slot_1' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_Slot) == 0x001900, "Member 'UABP_Bosco_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_RigidBody) == 0x001950, "Member 'UABP_Bosco_C::AnimGraphNode_RigidBody' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_LocalToComponentSpace) == 0x002180, "Member 'UABP_Bosco_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UABP_Bosco_C, AnimGraphNode_ComponentToLocalSpace) == 0x0021A0, "Member 'UABP_Bosco_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");

}

