#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Basic_ArrowButton02

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Basic_ArrowButton02.Basic_ArrowButton02_C
// 0x0030 (0x0290 - 0x0260)
class UBasic_ArrowButton02_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Arrow_bracket;                                     // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Arrow;                                      // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnClicked;                                         // 0x0278(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	float                                         ButtonAngle;                                       // 0x0288(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime);
	void BndEvt__Button_1_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__button_arrow_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__button_arrow_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__button_arrow_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__button_arrow_K2Node_ComponentBoundEvent_4_OnButtonReleasedEvent__DelegateSignature();
	void ExecuteUbergraph_Basic_ArrowButton02(int32 EntryPoint);
	void OnClicked__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Basic_ArrowButton02_C">();
	}
	static class UBasic_ArrowButton02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBasic_ArrowButton02_C>();
	}
};
static_assert(alignof(UBasic_ArrowButton02_C) == 0x000008, "Wrong alignment on UBasic_ArrowButton02_C");
static_assert(sizeof(UBasic_ArrowButton02_C) == 0x000290, "Wrong size on UBasic_ArrowButton02_C");
static_assert(offsetof(UBasic_ArrowButton02_C, UberGraphFrame) == 0x000260, "Member 'UBasic_ArrowButton02_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBasic_ArrowButton02_C, Arrow_bracket) == 0x000268, "Member 'UBasic_ArrowButton02_C::Arrow_bracket' has a wrong offset!");
static_assert(offsetof(UBasic_ArrowButton02_C, Button_Arrow) == 0x000270, "Member 'UBasic_ArrowButton02_C::Button_Arrow' has a wrong offset!");
static_assert(offsetof(UBasic_ArrowButton02_C, OnClicked) == 0x000278, "Member 'UBasic_ArrowButton02_C::OnClicked' has a wrong offset!");
static_assert(offsetof(UBasic_ArrowButton02_C, ButtonAngle) == 0x000288, "Member 'UBasic_ArrowButton02_C::ButtonAngle' has a wrong offset!");

}

