#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Basic_MenuLabel

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Slate_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "ENUM_CarbonTypeFace_structs.hpp"


namespace SDK::Params
{

// Function Basic_MenuLabel.Basic_MenuLabel_C.ExecuteUbergraph_Basic_MenuLabel
// 0x0040 (0x0040 - 0x0000)
struct Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MenuColors_OutputColor;                   // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_413C[0x3];                                     // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0018(0x0028)()
};
static_assert(alignof(Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel) == 0x000008, "Wrong alignment on Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel");
static_assert(sizeof(Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel) == 0x000040, "Wrong size on Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel");
static_assert(offsetof(Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel, EntryPoint) == 0x000000, "Member 'Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel::EntryPoint' has a wrong offset!");
static_assert(offsetof(Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel, CallFunc_MenuColors_OutputColor) == 0x000004, "Member 'Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel::CallFunc_MenuColors_OutputColor' has a wrong offset!");
static_assert(offsetof(Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel, K2Node_Event_IsDesignTime) == 0x000014, "Member 'Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel, K2Node_MakeStruct_SlateColor) == 0x000018, "Member 'Basic_MenuLabel_C_ExecuteUbergraph_Basic_MenuLabel::K2Node_MakeStruct_SlateColor' has a wrong offset!");

// Function Basic_MenuLabel.Basic_MenuLabel_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct Basic_MenuLabel_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Basic_MenuLabel_C_PreConstruct) == 0x000001, "Wrong alignment on Basic_MenuLabel_C_PreConstruct");
static_assert(sizeof(Basic_MenuLabel_C_PreConstruct) == 0x000001, "Wrong size on Basic_MenuLabel_C_PreConstruct");
static_assert(offsetof(Basic_MenuLabel_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'Basic_MenuLabel_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function Basic_MenuLabel.Basic_MenuLabel_C.SetText
// 0x0050 (0x0050 - 0x0000)
struct Basic_MenuLabel_C_SetText final
{
public:
	class FText                                   NewText;                                           // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          Temp_bool_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_413D[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0020(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x0038(0x0018)()
};
static_assert(alignof(Basic_MenuLabel_C_SetText) == 0x000008, "Wrong alignment on Basic_MenuLabel_C_SetText");
static_assert(sizeof(Basic_MenuLabel_C_SetText) == 0x000050, "Wrong size on Basic_MenuLabel_C_SetText");
static_assert(offsetof(Basic_MenuLabel_C_SetText, NewText) == 0x000000, "Member 'Basic_MenuLabel_C_SetText::NewText' has a wrong offset!");
static_assert(offsetof(Basic_MenuLabel_C_SetText, Temp_bool_Variable) == 0x000018, "Member 'Basic_MenuLabel_C_SetText::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(Basic_MenuLabel_C_SetText, CallFunc_TextToUpper_ReturnValue) == 0x000020, "Member 'Basic_MenuLabel_C_SetText::CallFunc_TextToUpper_ReturnValue' has a wrong offset!");
static_assert(offsetof(Basic_MenuLabel_C_SetText, K2Node_Select_Default) == 0x000038, "Member 'Basic_MenuLabel_C_SetText::K2Node_Select_Default' has a wrong offset!");

// Function Basic_MenuLabel.Basic_MenuLabel_C.SetFontSize
// 0x0060 (0x0060 - 0x0000)
struct Basic_MenuLabel_C_SetFontSize final
{
public:
	int32                                         InFontSize;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_413E[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo;                   // 0x0008(0x0058)(HasGetValueTypeHash)
};
static_assert(alignof(Basic_MenuLabel_C_SetFontSize) == 0x000008, "Wrong alignment on Basic_MenuLabel_C_SetFontSize");
static_assert(sizeof(Basic_MenuLabel_C_SetFontSize) == 0x000060, "Wrong size on Basic_MenuLabel_C_SetFontSize");
static_assert(offsetof(Basic_MenuLabel_C_SetFontSize, InFontSize) == 0x000000, "Member 'Basic_MenuLabel_C_SetFontSize::InFontSize' has a wrong offset!");
static_assert(offsetof(Basic_MenuLabel_C_SetFontSize, K2Node_MakeStruct_SlateFontInfo) == 0x000008, "Member 'Basic_MenuLabel_C_SetFontSize::K2Node_MakeStruct_SlateFontInfo' has a wrong offset!");

// Function Basic_MenuLabel.Basic_MenuLabel_C.SetTypeFace
// 0x0078 (0x0078 - 0x0000)
struct Basic_MenuLabel_C_SetTypeFace final
{
public:
	ENUM_CarbonTypeface                           Param_Typeface;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_413F[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateFontInfo                         K2Node_MakeStruct_SlateFontInfo;                   // 0x0020(0x0058)(HasGetValueTypeHash)
};
static_assert(alignof(Basic_MenuLabel_C_SetTypeFace) == 0x000008, "Wrong alignment on Basic_MenuLabel_C_SetTypeFace");
static_assert(sizeof(Basic_MenuLabel_C_SetTypeFace) == 0x000078, "Wrong size on Basic_MenuLabel_C_SetTypeFace");
static_assert(offsetof(Basic_MenuLabel_C_SetTypeFace, Param_Typeface) == 0x000000, "Member 'Basic_MenuLabel_C_SetTypeFace::Param_Typeface' has a wrong offset!");
static_assert(offsetof(Basic_MenuLabel_C_SetTypeFace, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000008, "Member 'Basic_MenuLabel_C_SetTypeFace::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");
static_assert(offsetof(Basic_MenuLabel_C_SetTypeFace, CallFunc_Conv_StringToName_ReturnValue) == 0x000018, "Member 'Basic_MenuLabel_C_SetTypeFace::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(Basic_MenuLabel_C_SetTypeFace, K2Node_MakeStruct_SlateFontInfo) == 0x000020, "Member 'Basic_MenuLabel_C_SetTypeFace::K2Node_MakeStruct_SlateFontInfo' has a wrong offset!");

// Function Basic_MenuLabel.Basic_MenuLabel_C.SetJustification
// 0x0001 (0x0001 - 0x0000)
struct Basic_MenuLabel_C_SetJustification final
{
public:
	ETextJustify                                  InJustification;                                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Basic_MenuLabel_C_SetJustification) == 0x000001, "Wrong alignment on Basic_MenuLabel_C_SetJustification");
static_assert(sizeof(Basic_MenuLabel_C_SetJustification) == 0x000001, "Wrong size on Basic_MenuLabel_C_SetJustification");
static_assert(offsetof(Basic_MenuLabel_C_SetJustification, InJustification) == 0x000000, "Member 'Basic_MenuLabel_C_SetJustification::InJustification' has a wrong offset!");

}

