#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BoscoVacuum

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FSD_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BoscoVacuum.BP_BoscoVacuum_C
// 0x0018 (0x0278 - 0x0260)
class ABP_BoscoVacuum_C final : public ADroneVacuumStream
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               ParticleSystem;                                    // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        VacuumSound;                                       // 0x0270(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveDestroyed();
	void Receive_OnAbilityDataSet();
	void ExecuteUbergraph_BP_BoscoVacuum(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BoscoVacuum_C">();
	}
	static class ABP_BoscoVacuum_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BoscoVacuum_C>();
	}
};
static_assert(alignof(ABP_BoscoVacuum_C) == 0x000008, "Wrong alignment on ABP_BoscoVacuum_C");
static_assert(sizeof(ABP_BoscoVacuum_C) == 0x000278, "Wrong size on ABP_BoscoVacuum_C");
static_assert(offsetof(ABP_BoscoVacuum_C, UberGraphFrame) == 0x000260, "Member 'ABP_BoscoVacuum_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_BoscoVacuum_C, ParticleSystem) == 0x000268, "Member 'ABP_BoscoVacuum_C::ParticleSystem' has a wrong offset!");
static_assert(offsetof(ABP_BoscoVacuum_C, VacuumSound) == 0x000270, "Member 'ABP_BoscoVacuum_C::VacuumSound' has a wrong offset!");

}

