#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FriendlyShredder

#include "Basic.hpp"

#include "BP_FriendlyShredder_classes.hpp"
#include "BP_FriendlyShredder_parameters.hpp"


namespace SDK
{

// Function BP_FriendlyShredder.BP_FriendlyShredder_C.BndEvt__HealthComponent_K2Node_ComponentBoundEvent_0_DeathSig__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UHealthComponentBase*             Param_HealthComponent                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FriendlyShredder_C::BndEvt__HealthComponent_K2Node_ComponentBoundEvent_0_DeathSig__DelegateSignature(class UHealthComponentBase* Param_HealthComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "BndEvt__HealthComponent_K2Node_ComponentBoundEvent_0_DeathSig__DelegateSignature");

	Params::BP_FriendlyShredder_C_BndEvt__HealthComponent_K2Node_ComponentBoundEvent_0_DeathSig__DelegateSignature Parms{};

	Parms.Param_HealthComponent = Param_HealthComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.BndEvt__BP_FriendlyShredder_InstantUsable_K2Node_ComponentBoundEvent_0_UsedBySignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class APlayerCharacter*                 User                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInputKeys                              Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FriendlyShredder_C::BndEvt__BP_FriendlyShredder_InstantUsable_K2Node_ComponentBoundEvent_0_UsedBySignature__DelegateSignature(class APlayerCharacter* User, EInputKeys Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "BndEvt__BP_FriendlyShredder_InstantUsable_K2Node_ComponentBoundEvent_0_UsedBySignature__DelegateSignature");

	Params::BP_FriendlyShredder_C_BndEvt__BP_FriendlyShredder_InstantUsable_K2Node_ComponentBoundEvent_0_UsedBySignature__DelegateSignature Parms{};

	Parms.User = User;
	Parms.Key = Key;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.BndEvt__BP_FriendlyShredder_MeleeAttack_K2Node_ComponentBoundEvent_1_MeleeAttackDelegate__DelegateSignature
// (BlueprintEvent)

void ABP_FriendlyShredder_C::BndEvt__BP_FriendlyShredder_MeleeAttack_K2Node_ComponentBoundEvent_1_MeleeAttackDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "BndEvt__BP_FriendlyShredder_MeleeAttack_K2Node_ComponentBoundEvent_1_MeleeAttackDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.GiveSpeedBoost
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_FriendlyShredder_C::GiveSpeedBoost()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "GiveSpeedBoost");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.RemoveSpeedBoost
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_FriendlyShredder_C::RemoveSpeedBoost()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "RemoveSpeedBoost");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FriendlyShredder_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "ReceiveTick");

	Params::BP_FriendlyShredder_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FriendlyShredder_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.HandleRotationToTarget
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FriendlyShredder_C::HandleRotationToTarget(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "HandleRotationToTarget");

	Params::BP_FriendlyShredder_C_HandleRotationToTarget Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.destroy
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DestroyedActor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FriendlyShredder_C::Destroy(class AActor* DestroyedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "destroy");

	Params::BP_FriendlyShredder_C_Destroy Parms{};

	Parms.DestroyedActor = DestroyedActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.PlayAccelerationSound
// (BlueprintCallable, BlueprintEvent)

void ABP_FriendlyShredder_C::PlayAccelerationSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "PlayAccelerationSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.OnMessageAI
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             TriggerName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FriendlyShredder_C::OnMessageAI(class FName TriggerName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "OnMessageAI");

	Params::BP_FriendlyShredder_C_OnMessageAI Parms{};

	Parms.TriggerName = TriggerName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FriendlyShredder.BP_FriendlyShredder_C.ExecuteUbergraph_BP_FriendlyShredder
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FriendlyShredder_C::ExecuteUbergraph_BP_FriendlyShredder(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FriendlyShredder_C", "ExecuteUbergraph_BP_FriendlyShredder");

	Params::BP_FriendlyShredder_C_ExecuteUbergraph_BP_FriendlyShredder Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

