#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUD_LaserPointerDisplay

#include "Basic.hpp"

#include "HUD_LaserPointerDisplay_classes.hpp"
#include "HUD_LaserPointerDisplay_parameters.hpp"


namespace SDK
{

// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.SetIconAndTint
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       Texture                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     Tint                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUD_LaserPointerDisplay_C::SetIconAndTint(class UTexture2D* Texture, const struct FLinearColor& Tint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "SetIconAndTint");

	Params::HUD_LaserPointerDisplay_C_SetIconAndTint Parms{};

	Parms.Texture = Texture;
	Parms.Tint = std::move(Tint);

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.UpdateCommands
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UHUD_LaserPointerDisplay_C::UpdateCommands()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "UpdateCommands");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.Finished_2FB3B1024A257294FCE363AC76E7AAF6
// (BlueprintCallable, BlueprintEvent)

void UHUD_LaserPointerDisplay_C::Finished_2FB3B1024A257294FCE363AC76E7AAF6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "Finished_2FB3B1024A257294FCE363AC76E7AAF6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.Point Of Interest
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       Texture                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     Tint                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUD_LaserPointerDisplay_C::Point_Of_Interest(class UTexture2D* Texture, const struct FLinearColor& Tint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "Point Of Interest");

	Params::HUD_LaserPointerDisplay_C_Point_Of_Interest Parms{};

	Parms.Texture = Texture;
	Parms.Tint = std::move(Tint);

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHUD_LaserPointerDisplay_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "PreConstruct");

	Params::HUD_LaserPointerDisplay_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.OnBoscoChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABosco*                           Bosco                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUD_LaserPointerDisplay_C::OnBoscoChanged(class ABosco* Bosco)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "OnBoscoChanged");

	Params::HUD_LaserPointerDisplay_C_OnBoscoChanged Parms{};

	Parms.Bosco = Bosco;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.StartScan
// (BlueprintCallable, BlueprintEvent)

void UHUD_LaserPointerDisplay_C::StartScan()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "StartScan");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.StopScan
// (BlueprintCallable, BlueprintEvent)

void UHUD_LaserPointerDisplay_C::StopScan()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "StopScan");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.OnUnEquipped
// (BlueprintCallable, BlueprintEvent)

void UHUD_LaserPointerDisplay_C::OnUnEquipped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "OnUnEquipped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.Update Display
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FHitResult                       Hit                                                    (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// float                                   Distance                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLaserPointerData                Data                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UHUD_LaserPointerDisplay_C::Update_Display(const struct FHitResult& Hit, float Distance, const struct FLaserPointerData& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "Update Display");

	Params::HUD_LaserPointerDisplay_C_Update_Display Parms{};

	Parms.Hit = std::move(Hit);
	Parms.Distance = Distance;
	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.OnEquipped
// (BlueprintCallable, BlueprintEvent)

void UHUD_LaserPointerDisplay_C::OnEquipped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "OnEquipped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UHUD_LaserPointerDisplay_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.StartShow
// (BlueprintCallable, BlueprintEvent)

void UHUD_LaserPointerDisplay_C::StartShow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "StartShow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.ExecuteUbergraph_HUD_LaserPointerDisplay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUD_LaserPointerDisplay_C::ExecuteUbergraph_HUD_LaserPointerDisplay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "ExecuteUbergraph_HUD_LaserPointerDisplay");

	Params::HUD_LaserPointerDisplay_C_ExecuteUbergraph_HUD_LaserPointerDisplay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUD_LaserPointerDisplay.HUD_LaserPointerDisplay_C.ScanComplete__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UHUD_LaserPointerDisplay_C::ScanComplete__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUD_LaserPointerDisplay_C", "ScanComplete__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

