#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Itm_DLC_Entry

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"
#include "FSD_structs.hpp"


namespace SDK::Params
{

// Function Itm_DLC_Entry.ITM_DLC_Entry_C.OnHoverBegin__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct ITM_DLC_Entry_C_OnHoverBegin__DelegateSignature final
{
public:
	class UITM_DLC_Entry_C*                       InEntry;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ITM_DLC_Entry_C_OnHoverBegin__DelegateSignature) == 0x000008, "Wrong alignment on ITM_DLC_Entry_C_OnHoverBegin__DelegateSignature");
static_assert(sizeof(ITM_DLC_Entry_C_OnHoverBegin__DelegateSignature) == 0x000008, "Wrong size on ITM_DLC_Entry_C_OnHoverBegin__DelegateSignature");
static_assert(offsetof(ITM_DLC_Entry_C_OnHoverBegin__DelegateSignature, InEntry) == 0x000000, "Member 'ITM_DLC_Entry_C_OnHoverBegin__DelegateSignature::InEntry' has a wrong offset!");

// Function Itm_DLC_Entry.ITM_DLC_Entry_C.OnHoverEnd__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct ITM_DLC_Entry_C_OnHoverEnd__DelegateSignature final
{
public:
	class UITM_DLC_Entry_C*                       InEntry;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ITM_DLC_Entry_C_OnHoverEnd__DelegateSignature) == 0x000008, "Wrong alignment on ITM_DLC_Entry_C_OnHoverEnd__DelegateSignature");
static_assert(sizeof(ITM_DLC_Entry_C_OnHoverEnd__DelegateSignature) == 0x000008, "Wrong size on ITM_DLC_Entry_C_OnHoverEnd__DelegateSignature");
static_assert(offsetof(ITM_DLC_Entry_C_OnHoverEnd__DelegateSignature, InEntry) == 0x000000, "Member 'ITM_DLC_Entry_C_OnHoverEnd__DelegateSignature::InEntry' has a wrong offset!");

// Function Itm_DLC_Entry.ITM_DLC_Entry_C.OnClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct ITM_DLC_Entry_C_OnClicked__DelegateSignature final
{
public:
	class UITM_DLC_Entry_C*                       InEntry;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ITM_DLC_Entry_C_OnClicked__DelegateSignature) == 0x000008, "Wrong alignment on ITM_DLC_Entry_C_OnClicked__DelegateSignature");
static_assert(sizeof(ITM_DLC_Entry_C_OnClicked__DelegateSignature) == 0x000008, "Wrong size on ITM_DLC_Entry_C_OnClicked__DelegateSignature");
static_assert(offsetof(ITM_DLC_Entry_C_OnClicked__DelegateSignature, InEntry) == 0x000000, "Member 'ITM_DLC_Entry_C_OnClicked__DelegateSignature::InEntry' has a wrong offset!");

// Function Itm_DLC_Entry.ITM_DLC_Entry_C.ExecuteUbergraph_ITM_DLC_Entry
// 0x0110 (0x0110 - 0x0000)
struct ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_422A[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_422B[0x2];                                     // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_OpenStorePage_ReturnValue;                // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsUnlocked_ReturnValue;                   // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_422C[0x2];                                     // 0x0026(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakVector2D_X;                          // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SelectVisibility_IsVisible;               // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SelectVisibility_VisibilityChanged;       // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              CallFunc_SelectVisibility_New_Visibility;          // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_422D[0x1];                                     // 0x0033(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_422E[0x3];                                     // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             CallFunc_GetBanner_16_9_ReturnValue;               // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Hover_OutChanged;                         // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Hover_OutChanged_1;                       // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_422F[0x2];                                     // 0x005A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x005C(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUnlocked_ReturnValue_1;                 // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SelectVisibility_IsVisible_1;             // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SelectVisibility_VisibilityChanged_1;     // 0x009A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              CallFunc_SelectVisibility_New_Visibility_1;        // 0x009B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4230[0x4];                                     // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UStatHat*                               CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x00A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UMediaPlayerWidget*                     K2Node_ComponentBoundEvent_InPlayerWidget;         // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMediaPlayerState                             K2Node_ComponentBoundEvent_InState;                // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4231[0x6];                                     // 0x00D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_2;              // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default;                             // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4232[0x4];                                     // 0x00E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAsyncManager*                          CallFunc_GetAsyncManager_ReturnValue;              // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAsyncManager*                          CallFunc_GetAsyncManager_ReturnValue_1;            // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_SyncLoadAsset_ReturnValue;                // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFileMediaSource*                       K2Node_DynamicCast_AsFile_Media_Source;            // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry) == 0x000008, "Wrong alignment on ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry");
static_assert(sizeof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry) == 0x000110, "Wrong size on ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, EntryPoint) == 0x000000, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::EntryPoint' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, Temp_bool_Variable) == 0x000004, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, Temp_int_Variable) == 0x000008, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, Temp_int_Variable_1) == 0x00000C, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_IsValid_ReturnValue_1) == 0x000011, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, K2Node_CreateDelegate_OutputDelegate) == 0x000014, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_OpenStorePage_ReturnValue) == 0x000024, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_OpenStorePage_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_IsUnlocked_ReturnValue) == 0x000025, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_IsUnlocked_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_BreakVector2D_X) == 0x000028, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_BreakVector2D_Y) == 0x00002C, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_SelectVisibility_IsVisible) == 0x000030, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_SelectVisibility_IsVisible' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_SelectVisibility_VisibilityChanged) == 0x000031, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_SelectVisibility_VisibilityChanged' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_SelectVisibility_New_Visibility) == 0x000032, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_SelectVisibility_New_Visibility' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000034, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000038, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, K2Node_Event_IsDesignTime) == 0x00003C, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_GetBanner_16_9_ReturnValue) == 0x000040, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_GetBanner_16_9_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_PlayAnimation_ReturnValue) == 0x000048, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_PlayAnimation_ReturnValue_1) == 0x000050, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_Hover_OutChanged) == 0x000058, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_Hover_OutChanged' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_Hover_OutChanged_1) == 0x000059, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_Hover_OutChanged_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, K2Node_Event_MyGeometry) == 0x00005C, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, K2Node_Event_InDeltaTime) == 0x000094, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_IsUnlocked_ReturnValue_1) == 0x000098, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_IsUnlocked_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_SelectVisibility_IsVisible_1) == 0x000099, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_SelectVisibility_IsVisible_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_SelectVisibility_VisibilityChanged_1) == 0x00009A, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_SelectVisibility_VisibilityChanged_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_SelectVisibility_New_Visibility_1) == 0x00009B, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_SelectVisibility_New_Visibility_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x0000A0, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_Concat_StrStr_ReturnValue) == 0x0000A8, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_Concat_StrStr_ReturnValue_1) == 0x0000B8, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, K2Node_ComponentBoundEvent_InPlayerWidget) == 0x0000C8, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::K2Node_ComponentBoundEvent_InPlayerWidget' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, K2Node_ComponentBoundEvent_InState) == 0x0000D0, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::K2Node_ComponentBoundEvent_InState' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0000D1, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_PlayAnimation_ReturnValue_2) == 0x0000D8, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_PlayAnimation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, K2Node_Select_Default) == 0x0000E0, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_GetAsyncManager_ReturnValue) == 0x0000E8, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_GetAsyncManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_GetAsyncManager_ReturnValue_1) == 0x0000F0, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_GetAsyncManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, CallFunc_SyncLoadAsset_ReturnValue) == 0x0000F8, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::CallFunc_SyncLoadAsset_ReturnValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, K2Node_DynamicCast_AsFile_Media_Source) == 0x000100, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::K2Node_DynamicCast_AsFile_Media_Source' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry, K2Node_DynamicCast_bSuccess) == 0x000108, "Member 'ITM_DLC_Entry_C_ExecuteUbergraph_ITM_DLC_Entry::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function Itm_DLC_Entry.ITM_DLC_Entry_C.BndEvt__ITM_DLC_Entry_UI_MediaPlayer_K2Node_ComponentBoundEvent_3_StateChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct ITM_DLC_Entry_C_BndEvt__ITM_DLC_Entry_UI_MediaPlayer_K2Node_ComponentBoundEvent_3_StateChanged__DelegateSignature final
{
public:
	class UMediaPlayerWidget*                     InPlayerWidget;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMediaPlayerState                             InState;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ITM_DLC_Entry_C_BndEvt__ITM_DLC_Entry_UI_MediaPlayer_K2Node_ComponentBoundEvent_3_StateChanged__DelegateSignature) == 0x000008, "Wrong alignment on ITM_DLC_Entry_C_BndEvt__ITM_DLC_Entry_UI_MediaPlayer_K2Node_ComponentBoundEvent_3_StateChanged__DelegateSignature");
static_assert(sizeof(ITM_DLC_Entry_C_BndEvt__ITM_DLC_Entry_UI_MediaPlayer_K2Node_ComponentBoundEvent_3_StateChanged__DelegateSignature) == 0x000010, "Wrong size on ITM_DLC_Entry_C_BndEvt__ITM_DLC_Entry_UI_MediaPlayer_K2Node_ComponentBoundEvent_3_StateChanged__DelegateSignature");
static_assert(offsetof(ITM_DLC_Entry_C_BndEvt__ITM_DLC_Entry_UI_MediaPlayer_K2Node_ComponentBoundEvent_3_StateChanged__DelegateSignature, InPlayerWidget) == 0x000000, "Member 'ITM_DLC_Entry_C_BndEvt__ITM_DLC_Entry_UI_MediaPlayer_K2Node_ComponentBoundEvent_3_StateChanged__DelegateSignature::InPlayerWidget' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_BndEvt__ITM_DLC_Entry_UI_MediaPlayer_K2Node_ComponentBoundEvent_3_StateChanged__DelegateSignature, InState) == 0x000008, "Member 'ITM_DLC_Entry_C_BndEvt__ITM_DLC_Entry_UI_MediaPlayer_K2Node_ComponentBoundEvent_3_StateChanged__DelegateSignature::InState' has a wrong offset!");

// Function Itm_DLC_Entry.ITM_DLC_Entry_C.Tick
// 0x003C (0x003C - 0x0000)
struct ITM_DLC_Entry_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ITM_DLC_Entry_C_Tick) == 0x000004, "Wrong alignment on ITM_DLC_Entry_C_Tick");
static_assert(sizeof(ITM_DLC_Entry_C_Tick) == 0x00003C, "Wrong size on ITM_DLC_Entry_C_Tick");
static_assert(offsetof(ITM_DLC_Entry_C_Tick, MyGeometry) == 0x000000, "Member 'ITM_DLC_Entry_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_Tick, InDeltaTime) == 0x000038, "Member 'ITM_DLC_Entry_C_Tick::InDeltaTime' has a wrong offset!");

// Function Itm_DLC_Entry.ITM_DLC_Entry_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct ITM_DLC_Entry_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ITM_DLC_Entry_C_PreConstruct) == 0x000001, "Wrong alignment on ITM_DLC_Entry_C_PreConstruct");
static_assert(sizeof(ITM_DLC_Entry_C_PreConstruct) == 0x000001, "Wrong size on ITM_DLC_Entry_C_PreConstruct");
static_assert(offsetof(ITM_DLC_Entry_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'ITM_DLC_Entry_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function Itm_DLC_Entry.ITM_DLC_Entry_C.Hover
// 0x0010 (0x0010 - 0x0000)
struct ITM_DLC_Entry_C_Hover final
{
public:
	bool                                          InHover;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          OutChanged;                                        // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EUMGSequencePlayMode                          Temp_byte_Variable;                                // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EUMGSequencePlayMode                          Temp_byte_Variable_1;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EUMGSequencePlayMode                          K2Node_Select_Default;                             // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_UpdateBool_ValueChanged;                  // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_UpdateBool_OutValue;                      // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ITM_DLC_Entry_C_Hover) == 0x000008, "Wrong alignment on ITM_DLC_Entry_C_Hover");
static_assert(sizeof(ITM_DLC_Entry_C_Hover) == 0x000010, "Wrong size on ITM_DLC_Entry_C_Hover");
static_assert(offsetof(ITM_DLC_Entry_C_Hover, InHover) == 0x000000, "Member 'ITM_DLC_Entry_C_Hover::InHover' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_Hover, OutChanged) == 0x000001, "Member 'ITM_DLC_Entry_C_Hover::OutChanged' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_Hover, Temp_bool_Variable) == 0x000002, "Member 'ITM_DLC_Entry_C_Hover::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_Hover, Temp_byte_Variable) == 0x000003, "Member 'ITM_DLC_Entry_C_Hover::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_Hover, Temp_byte_Variable_1) == 0x000004, "Member 'ITM_DLC_Entry_C_Hover::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_Hover, K2Node_Select_Default) == 0x000005, "Member 'ITM_DLC_Entry_C_Hover::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_Hover, CallFunc_UpdateBool_ValueChanged) == 0x000006, "Member 'ITM_DLC_Entry_C_Hover::CallFunc_UpdateBool_ValueChanged' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_Hover, CallFunc_UpdateBool_OutValue) == 0x000007, "Member 'ITM_DLC_Entry_C_Hover::CallFunc_UpdateBool_OutValue' has a wrong offset!");
static_assert(offsetof(ITM_DLC_Entry_C_Hover, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'ITM_DLC_Entry_C_Hover::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

}

