#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITM_SocialMediaButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ITM_SocialMediaButton.ITM_SocialMediaButton_C
// 0x0040 (0x02A0 - 0x0260)
class UITM_SocialMediaButton_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBasic_ButtonLargeImage_C*              Button;                                            // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTexture2D*                             Icon;                                              // 0x0270(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Description;                                       // 0x0278(0x0018)(Edit, BlueprintVisible)
	class FString                                 URL;                                               // 0x0290(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ITM_SocialMediaButton(int32 EntryPoint);
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void BndEvt__ITM_SocialMediaButton_Button_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();

	void CreateToolTip() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ITM_SocialMediaButton_C">();
	}
	static class UITM_SocialMediaButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UITM_SocialMediaButton_C>();
	}
};
static_assert(alignof(UITM_SocialMediaButton_C) == 0x000008, "Wrong alignment on UITM_SocialMediaButton_C");
static_assert(sizeof(UITM_SocialMediaButton_C) == 0x0002A0, "Wrong size on UITM_SocialMediaButton_C");
static_assert(offsetof(UITM_SocialMediaButton_C, UberGraphFrame) == 0x000260, "Member 'UITM_SocialMediaButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UITM_SocialMediaButton_C, Button) == 0x000268, "Member 'UITM_SocialMediaButton_C::Button' has a wrong offset!");
static_assert(offsetof(UITM_SocialMediaButton_C, Icon) == 0x000270, "Member 'UITM_SocialMediaButton_C::Icon' has a wrong offset!");
static_assert(offsetof(UITM_SocialMediaButton_C, Description) == 0x000278, "Member 'UITM_SocialMediaButton_C::Description' has a wrong offset!");
static_assert(offsetof(UITM_SocialMediaButton_C, URL) == 0x000290, "Member 'UITM_SocialMediaButton_C::URL' has a wrong offset!");

}

