#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITM_VanityTag_Category

#include "Basic.hpp"

#include "ITM_VanityTag_Category_classes.hpp"
#include "ITM_VanityTag_Category_parameters.hpp"


namespace SDK
{

// Function ITM_VanityTag_Category.ITM_VanityTag_Category_C.ClearSelected
// (Public, BlueprintCallable, BlueprintEvent)

void UITM_VanityTag_Category_C::ClearSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITM_VanityTag_Category_C", "ClearSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ITM_VanityTag_Category.ITM_VanityTag_Category_C.SetSelected
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UDetailedTag*>             InSelectedTags                                         (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UITM_VanityTag_Category_C::SetSelected(TArray<class UDetailedTag*>& InSelectedTags)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITM_VanityTag_Category_C", "SetSelected");

	Params::ITM_VanityTag_Category_C_SetSelected Parms{};

	Parms.InSelectedTags = std::move(InSelectedTags);

	UObject::ProcessEvent(Func, &Parms);

	InSelectedTags = std::move(Parms.InSelectedTags);
}


// Function ITM_VanityTag_Category.ITM_VanityTag_Category_C.EntryClicked
// (Private, BlueprintCallable, BlueprintEvent)

void UITM_VanityTag_Category_C::EntryClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITM_VanityTag_Category_C", "EntryClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ITM_VanityTag_Category.ITM_VanityTag_Category_C.GetSelected
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class UDetailedTag*>             OutSelected                                            (Parm, OutParm)

void UITM_VanityTag_Category_C::GetSelected(TArray<class UDetailedTag*>* OutSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITM_VanityTag_Category_C", "GetSelected");

	Params::ITM_VanityTag_Category_C_GetSelected Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutSelected != nullptr)
		*OutSelected = std::move(Parms.OutSelected);
}


// Function ITM_VanityTag_Category.ITM_VanityTag_Category_C.Set Category and Tags
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UDetailedTagCategory*             InCategory                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FDetailedTagSet                  InTagSet                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FDetailedTagSet                  InSelectedTagSet                                       (BlueprintVisible, BlueprintReadOnly, Parm)

void UITM_VanityTag_Category_C::Set_Category_and_Tags(class UDetailedTagCategory* InCategory, const struct FDetailedTagSet& InTagSet, const struct FDetailedTagSet& InSelectedTagSet)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITM_VanityTag_Category_C", "Set Category and Tags");

	Params::ITM_VanityTag_Category_C_Set_Category_and_Tags Parms{};

	Parms.InCategory = InCategory;
	Parms.InTagSet = std::move(InTagSet);
	Parms.InSelectedTagSet = std::move(InSelectedTagSet);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ITM_VanityTag_Category.ITM_VanityTag_Category_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UITM_VanityTag_Category_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITM_VanityTag_Category_C", "PreConstruct");

	Params::ITM_VanityTag_Category_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ITM_VanityTag_Category.ITM_VanityTag_Category_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UITM_VanityTag_Category_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITM_VanityTag_Category_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ITM_VanityTag_Category.ITM_VanityTag_Category_C.ExecuteUbergraph_ITM_VanityTag_Category
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UITM_VanityTag_Category_C::ExecuteUbergraph_ITM_VanityTag_Category(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITM_VanityTag_Category_C", "ExecuteUbergraph_ITM_VanityTag_Category");

	Params::ITM_VanityTag_Category_C_ExecuteUbergraph_ITM_VanityTag_Category Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ITM_VanityTag_Category.ITM_VanityTag_Category_C.OnSelectionChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UITM_VanityTag_Category_C::OnSelectionChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ITM_VanityTag_Category_C", "OnSelectionChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

