#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MAG_M1000

#include "Basic.hpp"

#include "MAG_M1000_classes.hpp"
#include "MAG_M1000_parameters.hpp"


namespace SDK
{

// Function MAG_M1000.MAG_M1000_C.OnSpawnRelease_Released
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool AMAG_M1000_C::OnSpawnRelease_Released()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MAG_M1000_C", "OnSpawnRelease_Released");

	Params::MAG_M1000_C_OnSpawnRelease_Released Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

