#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Options_Tab_Privacy

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "FSD_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Options_Tab_Privacy.Options_Tab_Privacy_C
// 0x0068 (0x02C8 - 0x0260)
class UOptions_Tab_Privacy_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             AggregatedText;                                    // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_Option_C*                        AppearOfflineOption;                               // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             GranularText;                                      // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_Option_C*                        OPT_AnonymousData;                                 // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_Option_C*                        OPT_PersonalData;                                  // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOptions_AnonymousMetrics_C*            Options_AnonymousMetrics;                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOptions_AppearOffline_C*               Options_AppearOffline;                             // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOptions_PersonalMetrics_C*             Options_PersonalMetrics;                           // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             PersonalText;                                      // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             SettingsChanged;                                   // 0x02B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UBasic_ToolTip_C*                       AppearOfflineOptionTooltip;                        // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SettingsChanged__DelegateSignature();
	void ExecuteUbergraph_Options_Tab_Privacy(int32 EntryPoint);
	void BndEvt__OPT_AnonymousData_K2Node_ComponentBoundEvent_221_OnHoveringEnd__DelegateSignature();
	void BndEvt__OPT_AnonymousData_K2Node_ComponentBoundEvent_215_OnHoveringBegin__DelegateSignature();
	void BndEvt__OPT_PersonalData_K2Node_ComponentBoundEvent_186_OnHoveringEnd__DelegateSignature();
	void BndEvt__OPT_PersonalData_K2Node_ComponentBoundEvent_170_OnHoveringBegin__DelegateSignature();
	void Construct();
	class UWidget* CreateAppearOfflineOptionToolTip();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Options_Tab_Privacy_C">();
	}
	static class UOptions_Tab_Privacy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOptions_Tab_Privacy_C>();
	}
};
static_assert(alignof(UOptions_Tab_Privacy_C) == 0x000008, "Wrong alignment on UOptions_Tab_Privacy_C");
static_assert(sizeof(UOptions_Tab_Privacy_C) == 0x0002C8, "Wrong size on UOptions_Tab_Privacy_C");
static_assert(offsetof(UOptions_Tab_Privacy_C, UberGraphFrame) == 0x000260, "Member 'UOptions_Tab_Privacy_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, AggregatedText) == 0x000268, "Member 'UOptions_Tab_Privacy_C::AggregatedText' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, AppearOfflineOption) == 0x000270, "Member 'UOptions_Tab_Privacy_C::AppearOfflineOption' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, GranularText) == 0x000278, "Member 'UOptions_Tab_Privacy_C::GranularText' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, OPT_AnonymousData) == 0x000280, "Member 'UOptions_Tab_Privacy_C::OPT_AnonymousData' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, OPT_PersonalData) == 0x000288, "Member 'UOptions_Tab_Privacy_C::OPT_PersonalData' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, Options_AnonymousMetrics) == 0x000290, "Member 'UOptions_Tab_Privacy_C::Options_AnonymousMetrics' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, Options_AppearOffline) == 0x000298, "Member 'UOptions_Tab_Privacy_C::Options_AppearOffline' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, Options_PersonalMetrics) == 0x0002A0, "Member 'UOptions_Tab_Privacy_C::Options_PersonalMetrics' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, PersonalText) == 0x0002A8, "Member 'UOptions_Tab_Privacy_C::PersonalText' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, SettingsChanged) == 0x0002B0, "Member 'UOptions_Tab_Privacy_C::SettingsChanged' has a wrong offset!");
static_assert(offsetof(UOptions_Tab_Privacy_C, AppearOfflineOptionTooltip) == 0x0002C0, "Member 'UOptions_Tab_Privacy_C::AppearOfflineOptionTooltip' has a wrong offset!");

}

