#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Options_Tab_GFX

#include "Basic.hpp"

#include "Options_Tab_GFX_classes.hpp"
#include "Options_Tab_GFX_parameters.hpp"


namespace SDK
{

// Function Options_Tab_GFX.Options_Tab_GFX_C.ExecuteUbergraph_Options_Tab_GFX
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOptions_Tab_GFX_C::ExecuteUbergraph_Options_Tab_GFX(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Options_Tab_GFX_C", "ExecuteUbergraph_Options_Tab_GFX");

	Params::Options_Tab_GFX_C_ExecuteUbergraph_Options_Tab_GFX Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Options_Tab_GFX.Options_Tab_GFX_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UOptions_Tab_GFX_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Options_Tab_GFX_C", "PreConstruct");

	Params::Options_Tab_GFX_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Options_Tab_GFX.Options_Tab_GFX_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UOptions_Tab_GFX_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Options_Tab_GFX_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Options_Tab_GFX.Options_Tab_GFX_C.SetPlatform
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFSDTargetPlatform                      Param_Platform                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOptions_Tab_GFX_C::SetPlatform(EFSDTargetPlatform Param_Platform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Options_Tab_GFX_C", "SetPlatform");

	Params::Options_Tab_GFX_C_SetPlatform Parms{};

	Parms.Param_Platform = Param_Platform;

	UObject::ProcessEvent(Func, &Parms);
}

}

