#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Options_GFX_MaxFPS

#include "Basic.hpp"


namespace SDK::Params
{

// Function Options_GFX_MaxFPS.Options_GFX_MaxFPS_C.ExecuteUbergraph_Options_GFX_MaxFPS
// 0x0070 (0x0070 - 0x0000)
struct Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_ComponentBoundEvent_Value;                  // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2974[0x3];                                     // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x000C(0x0010)(ZeroConstructor, NoDestructor)
	float                                         Temp_float_Variable;                               // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2975[0x3];                                     // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable_1;                             // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameUserSettings*                      CallFunc_GetGameUserSettings_ReturnValue;          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFrameRateLimit_ReturnValue;            // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2976[0x3];                                     // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameUserSettings*                      CallFunc_GetGameUserSettings_ReturnValue_1;        // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFSDGameInstance*                       CallFunc_GetFSDGameInstance_ReturnValue;           // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2977[0x4];                                     // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFSDGameInstance*                       CallFunc_GetFSDGameInstance_ReturnValue_1;         // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsChecked_ReturnValue;                 // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2978[0x3];                                     // 0x0059(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Get_Value_Value;                          // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_IsChecked;              // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2979[0x3];                                     // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default_1;                           // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Round_ReturnValue;                        // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS) == 0x000008, "Wrong alignment on Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS");
static_assert(sizeof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS) == 0x000070, "Wrong size on Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, EntryPoint) == 0x000000, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::EntryPoint' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, K2Node_ComponentBoundEvent_Value) == 0x000004, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::K2Node_ComponentBoundEvent_Value' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, Temp_bool_Variable) == 0x000008, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, K2Node_CreateDelegate_OutputDelegate) == 0x00000C, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, Temp_float_Variable) == 0x00001C, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, Temp_bool_Variable_1) == 0x000020, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, Temp_float_Variable_1) == 0x000024, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::Temp_float_Variable_1' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, CallFunc_GetGameUserSettings_ReturnValue) == 0x000028, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::CallFunc_GetGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, CallFunc_GetFrameRateLimit_ReturnValue) == 0x000030, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::CallFunc_GetFrameRateLimit_ReturnValue' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000034, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, CallFunc_GetGameUserSettings_ReturnValue_1) == 0x000038, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::CallFunc_GetGameUserSettings_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, CallFunc_GetFSDGameInstance_ReturnValue) == 0x000040, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::CallFunc_GetFSDGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, K2Node_Select_Default) == 0x000048, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, CallFunc_GetFSDGameInstance_ReturnValue_1) == 0x000050, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::CallFunc_GetFSDGameInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, CallFunc_GetIsChecked_ReturnValue) == 0x000058, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::CallFunc_GetIsChecked_ReturnValue' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, CallFunc_Get_Value_Value) == 0x00005C, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::CallFunc_Get_Value_Value' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, K2Node_ComponentBoundEvent_IsChecked) == 0x000060, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::K2Node_ComponentBoundEvent_IsChecked' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, K2Node_Select_Default_1) == 0x000064, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, CallFunc_Round_ReturnValue) == 0x000068, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::CallFunc_Round_ReturnValue' has a wrong offset!");
static_assert(offsetof(Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS, CallFunc_Conv_IntToFloat_ReturnValue) == 0x00006C, "Member 'Options_GFX_MaxFPS_C_ExecuteUbergraph_Options_GFX_MaxFPS::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");

// Function Options_GFX_MaxFPS.Options_GFX_MaxFPS_C.BndEvt__Basic_Slider_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct Options_GFX_MaxFPS_C_BndEvt__Basic_Slider_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature final
{
public:
	float                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Options_GFX_MaxFPS_C_BndEvt__Basic_Slider_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature) == 0x000004, "Wrong alignment on Options_GFX_MaxFPS_C_BndEvt__Basic_Slider_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature");
static_assert(sizeof(Options_GFX_MaxFPS_C_BndEvt__Basic_Slider_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature) == 0x000004, "Wrong size on Options_GFX_MaxFPS_C_BndEvt__Basic_Slider_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature");
static_assert(offsetof(Options_GFX_MaxFPS_C_BndEvt__Basic_Slider_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature, Value) == 0x000000, "Member 'Options_GFX_MaxFPS_C_BndEvt__Basic_Slider_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature::Value' has a wrong offset!");

// Function Options_GFX_MaxFPS.Options_GFX_MaxFPS_C.BndEvt__Basic_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct Options_GFX_MaxFPS_C_BndEvt__Basic_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature final
{
public:
	bool                                          IsChecked;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Options_GFX_MaxFPS_C_BndEvt__Basic_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on Options_GFX_MaxFPS_C_BndEvt__Basic_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature");
static_assert(sizeof(Options_GFX_MaxFPS_C_BndEvt__Basic_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature) == 0x000001, "Wrong size on Options_GFX_MaxFPS_C_BndEvt__Basic_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature");
static_assert(offsetof(Options_GFX_MaxFPS_C_BndEvt__Basic_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature, IsChecked) == 0x000000, "Member 'Options_GFX_MaxFPS_C_BndEvt__Basic_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckStateChanged__DelegateSignature::IsChecked' has a wrong offset!");

}

