#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_CircularProgressBar

#include "Basic.hpp"

#include "UI_CircularProgressBar_classes.hpp"
#include "UI_CircularProgressBar_parameters.hpp"


namespace SDK
{

// Function UI_CircularProgressBar.UI_CircularProgressBar_C.SetTintOpacity
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Param_TintOpacity                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CircularProgressBar_C::SetTintOpacity(float Param_TintOpacity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "SetTintOpacity");

	Params::UI_CircularProgressBar_C_SetTintOpacity Parms{};

	Parms.Param_TintOpacity = Param_TintOpacity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.SetTint
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ENUM_MenuColors                         Param_Tint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CircularProgressBar_C::SetTint(ENUM_MenuColors Param_Tint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "SetTint");

	Params::UI_CircularProgressBar_C_SetTint Parms{};

	Parms.Param_Tint = Param_Tint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.IncPercent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_Percent                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CircularProgressBar_C::IncPercent(float Value, float* Param_Percent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "IncPercent");

	Params::UI_CircularProgressBar_C_IncPercent Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Percent != nullptr)
		*Param_Percent = Parms.Param_Percent;
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.GetPercent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   Param_Percent                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CircularProgressBar_C::GetPercent(float* Param_Percent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "GetPercent");

	Params::UI_CircularProgressBar_C_GetPercent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Percent != nullptr)
		*Param_Percent = Parms.Param_Percent;
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.SetClockwise
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShowClockwise                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_CircularProgressBar_C::SetClockwise(bool ShowClockwise)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "SetClockwise");

	Params::UI_CircularProgressBar_C_SetClockwise Parms{};

	Parms.ShowClockwise = ShowClockwise;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.SetRingThickness
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CircularProgressBar_C::SetRingThickness(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "SetRingThickness");

	Params::UI_CircularProgressBar_C_SetRingThickness Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.SetRingRadius
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CircularProgressBar_C::SetRingRadius(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "SetRingRadius");

	Params::UI_CircularProgressBar_C_SetRingRadius Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.SetCompleteRange
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CircularProgressBar_C::SetCompleteRange(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "SetCompleteRange");

	Params::UI_CircularProgressBar_C_SetCompleteRange Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.SetStartAngle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CircularProgressBar_C::SetStartAngle(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "SetStartAngle");

	Params::UI_CircularProgressBar_C_SetStartAngle Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.CreateMaterial
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_CircularProgressBar_C::CreateMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "CreateMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.SetPercent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CircularProgressBar_C::SetPercent(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "SetPercent");

	Params::UI_CircularProgressBar_C_SetPercent Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUI_CircularProgressBar_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "PreConstruct");

	Params::UI_CircularProgressBar_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CircularProgressBar.UI_CircularProgressBar_C.ExecuteUbergraph_UI_CircularProgressBar
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CircularProgressBar_C::ExecuteUbergraph_UI_CircularProgressBar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CircularProgressBar_C", "ExecuteUbergraph_UI_CircularProgressBar");

	Params::UI_CircularProgressBar_C_ExecuteUbergraph_UI_CircularProgressBar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

