#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_DeathStats_View

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_DeathStats_View.UI_DeathStats_View_C
// 0x00C8 (0x0328 - 0x0260)
class UUI_DeathStats_View_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBasic_Menu_ColorBar_C*                 Basic_Menu_ColorBar;                               // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_Menu_ColorBar_C*                 Basic_Menu_ColorBar_C_0;                           // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBasic_ScrollBarBox_C*                  Basic_ScrollBarBox;                                // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           Header;                                            // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             HealthInsuranceEvaluation;                         // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             PlayerName;                                        // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           StatsParent;                                       // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_0;                                       // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_1;                                       // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_3;                                     // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class UUI_InfirmaryStats_Item_C*>      MissionStatLines;                                  // 0x02B8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class UMissionStat*>                   StoreModeStats;                                    // 0x02C8(0x0010)(Edit, BlueprintVisible)
	class UUI_InfirmaryStats_Item_C*              SelectedLine;                                      // 0x02D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          StoreMode;                                         // 0x02E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E89[0x3];                                      // 0x02E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         StoreModePause;                                    // 0x02E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UTexture2D*>                     CategoryIcons;                                     // 0x02E8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UTexture2D*>                     CategoryFilter;                                    // 0x02F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class AFSDPlayerController*                   OwningPlayer;                                      // 0x0308(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          StopStoreMode;                                     // 0x0310(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E8A[0x7];                                      // 0x0311(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFSDPlayerState*                        OwningState;                                       // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Debug;                                             // 0x0320(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UI_DeathStats_View(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void ReBuild();
	void ChangeName(const class FString& NewName);
	void SetStatsOwner(class AFSDPlayerState* Player_State);
	void Set_Selected_Item(class UUI_InfirmaryStats_Item_C* Param_SelectedLine);
	void Store_Mode(int32 Param_Index);
	void GetMissionStats(TArray<class UMissionStat*>* Assets);
	void SortStats(TArray<class UMissionStat*>& InStats, TArray<class UTexture2D*>* Categories, TArray<class UMissionStat*>* Sorted_Stats);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_DeathStats_View_C">();
	}
	static class UUI_DeathStats_View_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_DeathStats_View_C>();
	}
};
static_assert(alignof(UUI_DeathStats_View_C) == 0x000008, "Wrong alignment on UUI_DeathStats_View_C");
static_assert(sizeof(UUI_DeathStats_View_C) == 0x000328, "Wrong size on UUI_DeathStats_View_C");
static_assert(offsetof(UUI_DeathStats_View_C, UberGraphFrame) == 0x000260, "Member 'UUI_DeathStats_View_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, Basic_Menu_ColorBar) == 0x000268, "Member 'UUI_DeathStats_View_C::Basic_Menu_ColorBar' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, Basic_Menu_ColorBar_C_0) == 0x000270, "Member 'UUI_DeathStats_View_C::Basic_Menu_ColorBar_C_0' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, Basic_ScrollBarBox) == 0x000278, "Member 'UUI_DeathStats_View_C::Basic_ScrollBarBox' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, Header) == 0x000280, "Member 'UUI_DeathStats_View_C::Header' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, HealthInsuranceEvaluation) == 0x000288, "Member 'UUI_DeathStats_View_C::HealthInsuranceEvaluation' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, PlayerName) == 0x000290, "Member 'UUI_DeathStats_View_C::PlayerName' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, StatsParent) == 0x000298, "Member 'UUI_DeathStats_View_C::StatsParent' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, TextBlock_0) == 0x0002A0, "Member 'UUI_DeathStats_View_C::TextBlock_0' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, TextBlock_1) == 0x0002A8, "Member 'UUI_DeathStats_View_C::TextBlock_1' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, VerticalBox_3) == 0x0002B0, "Member 'UUI_DeathStats_View_C::VerticalBox_3' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, MissionStatLines) == 0x0002B8, "Member 'UUI_DeathStats_View_C::MissionStatLines' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, StoreModeStats) == 0x0002C8, "Member 'UUI_DeathStats_View_C::StoreModeStats' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, SelectedLine) == 0x0002D8, "Member 'UUI_DeathStats_View_C::SelectedLine' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, StoreMode) == 0x0002E0, "Member 'UUI_DeathStats_View_C::StoreMode' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, StoreModePause) == 0x0002E4, "Member 'UUI_DeathStats_View_C::StoreModePause' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, CategoryIcons) == 0x0002E8, "Member 'UUI_DeathStats_View_C::CategoryIcons' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, CategoryFilter) == 0x0002F8, "Member 'UUI_DeathStats_View_C::CategoryFilter' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, OwningPlayer) == 0x000308, "Member 'UUI_DeathStats_View_C::OwningPlayer' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, StopStoreMode) == 0x000310, "Member 'UUI_DeathStats_View_C::StopStoreMode' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, OwningState) == 0x000318, "Member 'UUI_DeathStats_View_C::OwningState' has a wrong offset!");
static_assert(offsetof(UUI_DeathStats_View_C, Debug) == 0x000320, "Member 'UUI_DeathStats_View_C::Debug' has a wrong offset!");

}

