#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ForceSeasonEvent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_ForceSeasonEvent.UI_ForceSeasonEvent_C
// 0x0030 (0x0290 - 0x0260)
class UUI_ForceSeasonEvent_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UComboBoxString*                        ComboBoxString_45;                                 // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 NewVar_0;                                          // 0x0270(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<TSoftObjectPtr<class USpecialEvent>>   Events;                                            // 0x0280(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void BndEvt__ComboBoxString_45_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void Construct();
	void ExecuteUbergraph_UI_ForceSeasonEvent(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_ForceSeasonEvent_C">();
	}
	static class UUI_ForceSeasonEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ForceSeasonEvent_C>();
	}
};
static_assert(alignof(UUI_ForceSeasonEvent_C) == 0x000008, "Wrong alignment on UUI_ForceSeasonEvent_C");
static_assert(sizeof(UUI_ForceSeasonEvent_C) == 0x000290, "Wrong size on UUI_ForceSeasonEvent_C");
static_assert(offsetof(UUI_ForceSeasonEvent_C, UberGraphFrame) == 0x000260, "Member 'UUI_ForceSeasonEvent_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_ForceSeasonEvent_C, ComboBoxString_45) == 0x000268, "Member 'UUI_ForceSeasonEvent_C::ComboBoxString_45' has a wrong offset!");
static_assert(offsetof(UUI_ForceSeasonEvent_C, NewVar_0) == 0x000270, "Member 'UUI_ForceSeasonEvent_C::NewVar_0' has a wrong offset!");
static_assert(offsetof(UUI_ForceSeasonEvent_C, Events) == 0x000280, "Member 'UUI_ForceSeasonEvent_C::Events' has a wrong offset!");

}

