#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_HazPlus_Icon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FSD_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_HazPlus_Icon.UI_HazPlus_Icon_C
// 0x0048 (0x02A8 - 0x0260)
class UUI_HazPlus_Icon_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBasic_Label_C*                         Amount_Label;                                      // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               Content_SizeBox;                                   // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon_Image;                                        // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Root_Overlay;                                      // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FDifficultyMutatorItem                 Mutator;                                           // 0x0288(0x0010)(Edit, BlueprintVisible, NoDestructor, ExposeOnSpawn)
	int32                                         Icon_Size;                                         // 0x0298(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Font_Size;                                         // 0x029C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Text_Offset;                                       // 0x02A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IconActive;                                        // 0x02A4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_UI_HazPlus_Icon(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetMutator(const struct FDifficultyMutatorItem& InMutator);
	void SetCount(int32 InCount);
	void SetSize(int32 InIconSize, int32 InFontSize, int32 InTextOffset);
	bool IsMutatorType(const struct FDifficultyMutatorItem& InMutator);
	void Set_Icon_Active(bool InIconActive);
	void GetMutator(struct FDifficultyMutatorItem* OutMutator);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_HazPlus_Icon_C">();
	}
	static class UUI_HazPlus_Icon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_HazPlus_Icon_C>();
	}
};
static_assert(alignof(UUI_HazPlus_Icon_C) == 0x000008, "Wrong alignment on UUI_HazPlus_Icon_C");
static_assert(sizeof(UUI_HazPlus_Icon_C) == 0x0002A8, "Wrong size on UUI_HazPlus_Icon_C");
static_assert(offsetof(UUI_HazPlus_Icon_C, UberGraphFrame) == 0x000260, "Member 'UUI_HazPlus_Icon_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_HazPlus_Icon_C, Amount_Label) == 0x000268, "Member 'UUI_HazPlus_Icon_C::Amount_Label' has a wrong offset!");
static_assert(offsetof(UUI_HazPlus_Icon_C, Content_SizeBox) == 0x000270, "Member 'UUI_HazPlus_Icon_C::Content_SizeBox' has a wrong offset!");
static_assert(offsetof(UUI_HazPlus_Icon_C, Icon_Image) == 0x000278, "Member 'UUI_HazPlus_Icon_C::Icon_Image' has a wrong offset!");
static_assert(offsetof(UUI_HazPlus_Icon_C, Root_Overlay) == 0x000280, "Member 'UUI_HazPlus_Icon_C::Root_Overlay' has a wrong offset!");
static_assert(offsetof(UUI_HazPlus_Icon_C, Mutator) == 0x000288, "Member 'UUI_HazPlus_Icon_C::Mutator' has a wrong offset!");
static_assert(offsetof(UUI_HazPlus_Icon_C, Icon_Size) == 0x000298, "Member 'UUI_HazPlus_Icon_C::Icon_Size' has a wrong offset!");
static_assert(offsetof(UUI_HazPlus_Icon_C, Font_Size) == 0x00029C, "Member 'UUI_HazPlus_Icon_C::Font_Size' has a wrong offset!");
static_assert(offsetof(UUI_HazPlus_Icon_C, Text_Offset) == 0x0002A0, "Member 'UUI_HazPlus_Icon_C::Text_Offset' has a wrong offset!");
static_assert(offsetof(UUI_HazPlus_Icon_C, IconActive) == 0x0002A4, "Member 'UUI_HazPlus_Icon_C::IconActive' has a wrong offset!");

}

