#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WPN_Revolver

#include "Basic.hpp"

#include "FSD_structs.hpp"


namespace SDK::Params
{

// Function WPN_Revolver.WPN_Revolver_C.OnSpreadChanged_Event_0
// 0x000C (0x000C - 0x0000)
struct WPN_Revolver_C_OnSpreadChanged_Event_0 final
{
public:
	float                                         HorizontalSpread;                                  // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         VerticalSpread;                                    // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsAtRest;                                          // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WPN_Revolver_C_OnSpreadChanged_Event_0) == 0x000004, "Wrong alignment on WPN_Revolver_C_OnSpreadChanged_Event_0");
static_assert(sizeof(WPN_Revolver_C_OnSpreadChanged_Event_0) == 0x00000C, "Wrong size on WPN_Revolver_C_OnSpreadChanged_Event_0");
static_assert(offsetof(WPN_Revolver_C_OnSpreadChanged_Event_0, HorizontalSpread) == 0x000000, "Member 'WPN_Revolver_C_OnSpreadChanged_Event_0::HorizontalSpread' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_OnSpreadChanged_Event_0, VerticalSpread) == 0x000004, "Member 'WPN_Revolver_C_OnSpreadChanged_Event_0::VerticalSpread' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_OnSpreadChanged_Event_0, IsAtRest) == 0x000008, "Member 'WPN_Revolver_C_OnSpreadChanged_Event_0::IsAtRest' has a wrong offset!");

// Function WPN_Revolver.WPN_Revolver_C.OnSkinChanged
// 0x0008 (0x0008 - 0x0000)
struct WPN_Revolver_C_OnSkinChanged final
{
public:
	class USkinEffect*                            Skin;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WPN_Revolver_C_OnSkinChanged) == 0x000008, "Wrong alignment on WPN_Revolver_C_OnSkinChanged");
static_assert(sizeof(WPN_Revolver_C_OnSkinChanged) == 0x000008, "Wrong size on WPN_Revolver_C_OnSkinChanged");
static_assert(offsetof(WPN_Revolver_C_OnSkinChanged, Skin) == 0x000000, "Member 'WPN_Revolver_C_OnSkinChanged::Skin' has a wrong offset!");

// Function WPN_Revolver.WPN_Revolver_C.ExecuteUbergraph_WPN_Revolver
// 0x0098 (0x0098 - 0x0000)
struct WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51D9[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_GetUserWidgetObject_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWeaponDisplay_Base_AmmoCount_C*        K2Node_DynamicCast_AsWeapon_Display_Base_Ammo_Count; // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsFirstPerson_ReturnValue;                // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51DA[0x2];                                     // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_CustomEvent_HorizontalSpread;               // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_VerticalSpread;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_isAtRest;                       // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51DB[0x3];                                     // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_FloatToString_ReturnValue;           // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51DC[0x4];                                     // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_FloatToString_ReturnValue_1;         // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51DD[0x7];                                     // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51DE[0x7];                                     // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51DF[0x7];                                     // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USkinEffect*                            K2Node_Event_skin;                                 // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EItemSkinType                                 CallFunc_GetSkinType_ReturnValue;                  // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver) == 0x000008, "Wrong alignment on WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver");
static_assert(sizeof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver) == 0x000098, "Wrong size on WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, EntryPoint) == 0x000000, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::EntryPoint' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_GetUserWidgetObject_ReturnValue) == 0x000008, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_GetUserWidgetObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, K2Node_DynamicCast_AsWeapon_Display_Base_Ammo_Count) == 0x000010, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::K2Node_DynamicCast_AsWeapon_Display_Base_Ammo_Count' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_IsFirstPerson_ReturnValue) == 0x000019, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_IsFirstPerson_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, K2Node_CustomEvent_HorizontalSpread) == 0x00001C, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::K2Node_CustomEvent_HorizontalSpread' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, K2Node_CustomEvent_VerticalSpread) == 0x000020, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::K2Node_CustomEvent_VerticalSpread' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, K2Node_CustomEvent_isAtRest) == 0x000024, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::K2Node_CustomEvent_isAtRest' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_Conv_FloatToString_ReturnValue) == 0x000028, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_Conv_FloatToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000038, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_Conv_FloatToString_ReturnValue_1) == 0x000040, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_Conv_FloatToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000050, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_Concat_StrStr_ReturnValue) == 0x000058, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x000068, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000070, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_BooleanOR_ReturnValue) == 0x000080, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, K2Node_Event_skin) == 0x000088, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::K2Node_Event_skin' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, CallFunc_GetSkinType_ReturnValue) == 0x000090, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::CallFunc_GetSkinType_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver, K2Node_SwitchEnum_CmpSuccess) == 0x000091, "Member 'WPN_Revolver_C_ExecuteUbergraph_WPN_Revolver::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function WPN_Revolver.WPN_Revolver_C.Receive_GetTPAnimationEventMesh
// 0x0008 (0x0008 - 0x0000)
struct WPN_Revolver_C_Receive_GetTPAnimationEventMesh final
{
public:
	class UStaticMeshComponent*                   ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WPN_Revolver_C_Receive_GetTPAnimationEventMesh) == 0x000008, "Wrong alignment on WPN_Revolver_C_Receive_GetTPAnimationEventMesh");
static_assert(sizeof(WPN_Revolver_C_Receive_GetTPAnimationEventMesh) == 0x000008, "Wrong size on WPN_Revolver_C_Receive_GetTPAnimationEventMesh");
static_assert(offsetof(WPN_Revolver_C_Receive_GetTPAnimationEventMesh, ReturnValue) == 0x000000, "Member 'WPN_Revolver_C_Receive_GetTPAnimationEventMesh::ReturnValue' has a wrong offset!");

// Function WPN_Revolver.WPN_Revolver_C.Receive_GetFPAnimationEventMesh
// 0x0008 (0x0008 - 0x0000)
struct WPN_Revolver_C_Receive_GetFPAnimationEventMesh final
{
public:
	class UFirstPersonStaticMeshComponent*        ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WPN_Revolver_C_Receive_GetFPAnimationEventMesh) == 0x000008, "Wrong alignment on WPN_Revolver_C_Receive_GetFPAnimationEventMesh");
static_assert(sizeof(WPN_Revolver_C_Receive_GetFPAnimationEventMesh) == 0x000008, "Wrong size on WPN_Revolver_C_Receive_GetFPAnimationEventMesh");
static_assert(offsetof(WPN_Revolver_C_Receive_GetFPAnimationEventMesh, ReturnValue) == 0x000000, "Member 'WPN_Revolver_C_Receive_GetFPAnimationEventMesh::ReturnValue' has a wrong offset!");

// Function WPN_Revolver.WPN_Revolver_C.GetGearStatEntry
// 0x08C0 (0x08C0 - 0x0000)
struct WPN_Revolver_C_GetGearStatEntry final
{
public:
	class AFSDPlayerState*                        PlayerState;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FGearStatEntry>                 Stats;                                             // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetUpgradeName_ReturnValue;               // 0x0020(0x0018)()
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue_1;             // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGearStatEntry                         CallFunc_UPGDESC_Generic_GearStatEntry;            // 0x0040(0x0068)()
	bool                                          CallFunc_UPGDESC_Generic_HasUpgradedValue;         // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51E0[0x7];                                     // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue_2;             // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51E1[0x4];                                     // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetUpgradeName_ReturnValue_1;             // 0x00C0(0x0018)()
	struct FGearStatEntry                         CallFunc_UPGDESC_Generic_GearStatEntry_1;          // 0x00D8(0x0068)()
	bool                                          CallFunc_UPGDESC_Generic_HasUpgradedValue_1;       // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51E2[0x7];                                     // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_Generic_GearStatEntry_2;          // 0x0148(0x0068)()
	bool                                          CallFunc_UPGDESC_Generic_HasUpgradedValue_2;       // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51E3[0x3];                                     // 0x01B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_2;                  // 0x01B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51E4[0x4];                                     // 0x01BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue_3;             // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGearStatEntry                         CallFunc_UPGDESC_DamageBonus_Random_GearStatEntry; // 0x01C8(0x0068)()
	bool                                          CallFunc_UPGDESC_DamageBonus_Random_HasUpgradedValue; // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51E5[0x3];                                     // 0x0231(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_3;                  // 0x0234(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<EAmmoDrivenWeapnUpgradeType>           K2Node_MakeArray_Array;                            // 0x0238(0x0010)(ReferenceParm)
	class FText                                   CallFunc_GetUpgradeName_ReturnValue_2;             // 0x0248(0x0018)()
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue_4;             // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGearStatEntry                         CallFunc_UPGDESC_AmmoDriven_GearStatEntry;         // 0x0268(0x0068)()
	bool                                          CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades;        // 0x02D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51E6[0x7];                                     // 0x02D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_HitScan_GearStatEntry;            // 0x02D8(0x0068)()
	bool                                          CallFunc_UPGDESC_HitScan_HasAnyUpgrades;           // 0x0340(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51E7[0x3];                                     // 0x0341(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_4;                  // 0x0344(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_5;                  // 0x0348(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51E8[0x4];                                     // 0x034C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue_5;             // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGearStatEntry                         CallFunc_UPGDESC_Damage_GearStatEntry;             // 0x0358(0x0068)()
	bool                                          CallFunc_UPGDESC_Damage_HasUpgradedValue;          // 0x03C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51E9[0x3];                                     // 0x03C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_6;                  // 0x03C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGearStatEntry                         CallFunc_UPGDESC_HitScan_GearStatEntry_1;          // 0x03C8(0x0068)()
	bool                                          CallFunc_UPGDESC_HitScan_HasAnyUpgrades_1;         // 0x0430(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51EA[0x7];                                     // 0x0431(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_HitScan_GearStatEntry_2;          // 0x0438(0x0068)()
	bool                                          CallFunc_UPGDESC_HitScan_HasAnyUpgrades_2;         // 0x04A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51EB[0x3];                                     // 0x04A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_7;                  // 0x04A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_8;                  // 0x04A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51EC[0x4];                                     // 0x04AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_Damage_GearStatEntry_1;           // 0x04B0(0x0068)()
	bool                                          CallFunc_UPGDESC_Damage_HasUpgradedValue_1;        // 0x0518(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51ED[0x7];                                     // 0x0519(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_Damage_GearStatEntry_2;           // 0x0520(0x0068)()
	bool                                          CallFunc_UPGDESC_Damage_HasUpgradedValue_2;        // 0x0588(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51EE[0x3];                                     // 0x0589(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_9;                  // 0x058C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_10;                 // 0x0590(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51EF[0x4];                                     // 0x0594(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_HitScan_GearStatEntry_3;          // 0x0598(0x0068)()
	bool                                          CallFunc_UPGDESC_HitScan_HasAnyUpgrades_3;         // 0x0600(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51F0[0x7];                                     // 0x0601(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_Damage_GearStatEntry_3;           // 0x0608(0x0068)()
	bool                                          CallFunc_UPGDESC_Damage_HasUpgradedValue_3;        // 0x0670(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51F1[0x3];                                     // 0x0671(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_11;                 // 0x0674(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_12;                 // 0x0678(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51F2[0x4];                                     // 0x067C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_Damage_GearStatEntry_4;           // 0x0680(0x0068)()
	bool                                          CallFunc_UPGDESC_Damage_HasUpgradedValue_4;        // 0x06E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51F3[0x7];                                     // 0x06E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_Damage_GearStatEntry_5;           // 0x06F0(0x0068)()
	bool                                          CallFunc_UPGDESC_Damage_HasUpgradedValue_5;        // 0x0758(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51F4[0x3];                                     // 0x0759(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_13;                 // 0x075C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_14;                 // 0x0760(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51F5[0x4];                                     // 0x0764(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_Damage_GearStatEntry_6;           // 0x0768(0x0068)()
	bool                                          CallFunc_UPGDESC_Damage_HasUpgradedValue_6;        // 0x07D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51F6[0x7];                                     // 0x07D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_DamageBonus_TargetStateBonus_GearStatEntry; // 0x07D8(0x0068)()
	bool                                          CallFunc_UPGDESC_DamageBonus_TargetStateBonus_HasUpgradedValue; // 0x0840(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51F7[0x3];                                     // 0x0841(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_15;                 // 0x0844(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_16;                 // 0x0848(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51F8[0x4];                                     // 0x084C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGearStatEntry                         CallFunc_UPGDESC_DamageBonus_TargetTypeBonus_GearStatEntry; // 0x0850(0x0068)()
	bool                                          CallFunc_UPGDESC_DamageBonus_TargetTypeBonus_HasUpgradedValue; // 0x08B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51F9[0x3];                                     // 0x08B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_17;                 // 0x08BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WPN_Revolver_C_GetGearStatEntry) == 0x000008, "Wrong alignment on WPN_Revolver_C_GetGearStatEntry");
static_assert(sizeof(WPN_Revolver_C_GetGearStatEntry) == 0x0008C0, "Wrong size on WPN_Revolver_C_GetGearStatEntry");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, PlayerState) == 0x000000, "Member 'WPN_Revolver_C_GetGearStatEntry::PlayerState' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, Stats) == 0x000008, "Member 'WPN_Revolver_C_GetGearStatEntry::Stats' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_GetObjectClass_ReturnValue) == 0x000018, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_GetUpgradeName_ReturnValue) == 0x000020, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_GetUpgradeName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_GetObjectClass_ReturnValue_1) == 0x000038, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_GetObjectClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Generic_GearStatEntry) == 0x000040, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Generic_GearStatEntry' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Generic_HasUpgradedValue) == 0x0000A8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Generic_HasUpgradedValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_GetObjectClass_ReturnValue_2) == 0x0000B0, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_GetObjectClass_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue) == 0x0000B8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_GetUpgradeName_ReturnValue_1) == 0x0000C0, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_GetUpgradeName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Generic_GearStatEntry_1) == 0x0000D8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Generic_GearStatEntry_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Generic_HasUpgradedValue_1) == 0x000140, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Generic_HasUpgradedValue_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Generic_GearStatEntry_2) == 0x000148, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Generic_GearStatEntry_2' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Generic_HasUpgradedValue_2) == 0x0001B0, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Generic_HasUpgradedValue_2' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_1) == 0x0001B4, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_2) == 0x0001B8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_GetObjectClass_ReturnValue_3) == 0x0001C0, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_GetObjectClass_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_DamageBonus_Random_GearStatEntry) == 0x0001C8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_DamageBonus_Random_GearStatEntry' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_DamageBonus_Random_HasUpgradedValue) == 0x000230, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_DamageBonus_Random_HasUpgradedValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_3) == 0x000234, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, K2Node_MakeArray_Array) == 0x000238, "Member 'WPN_Revolver_C_GetGearStatEntry::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_GetUpgradeName_ReturnValue_2) == 0x000248, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_GetUpgradeName_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_GetObjectClass_ReturnValue_4) == 0x000260, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_GetObjectClass_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_AmmoDriven_GearStatEntry) == 0x000268, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_AmmoDriven_GearStatEntry' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades) == 0x0002D0, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_AmmoDriven_HasAnyUpgrades' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_HitScan_GearStatEntry) == 0x0002D8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_HitScan_GearStatEntry' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_HitScan_HasAnyUpgrades) == 0x000340, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_HitScan_HasAnyUpgrades' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_4) == 0x000344, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_5) == 0x000348, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_GetObjectClass_ReturnValue_5) == 0x000350, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_GetObjectClass_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_GearStatEntry) == 0x000358, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_GearStatEntry' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_HasUpgradedValue) == 0x0003C0, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_HasUpgradedValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_6) == 0x0003C4, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_HitScan_GearStatEntry_1) == 0x0003C8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_HitScan_GearStatEntry_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_HitScan_HasAnyUpgrades_1) == 0x000430, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_HitScan_HasAnyUpgrades_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_HitScan_GearStatEntry_2) == 0x000438, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_HitScan_GearStatEntry_2' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_HitScan_HasAnyUpgrades_2) == 0x0004A0, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_HitScan_HasAnyUpgrades_2' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_7) == 0x0004A4, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_8) == 0x0004A8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_GearStatEntry_1) == 0x0004B0, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_GearStatEntry_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_HasUpgradedValue_1) == 0x000518, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_HasUpgradedValue_1' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_GearStatEntry_2) == 0x000520, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_GearStatEntry_2' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_HasUpgradedValue_2) == 0x000588, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_HasUpgradedValue_2' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_9) == 0x00058C, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_10) == 0x000590, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_HitScan_GearStatEntry_3) == 0x000598, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_HitScan_GearStatEntry_3' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_HitScan_HasAnyUpgrades_3) == 0x000600, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_HitScan_HasAnyUpgrades_3' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_GearStatEntry_3) == 0x000608, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_GearStatEntry_3' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_HasUpgradedValue_3) == 0x000670, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_HasUpgradedValue_3' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_11) == 0x000674, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_12) == 0x000678, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_GearStatEntry_4) == 0x000680, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_GearStatEntry_4' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_HasUpgradedValue_4) == 0x0006E8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_HasUpgradedValue_4' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_GearStatEntry_5) == 0x0006F0, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_GearStatEntry_5' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_HasUpgradedValue_5) == 0x000758, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_HasUpgradedValue_5' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_13) == 0x00075C, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_14) == 0x000760, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_GearStatEntry_6) == 0x000768, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_GearStatEntry_6' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_Damage_HasUpgradedValue_6) == 0x0007D0, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_Damage_HasUpgradedValue_6' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_DamageBonus_TargetStateBonus_GearStatEntry) == 0x0007D8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_DamageBonus_TargetStateBonus_GearStatEntry' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_DamageBonus_TargetStateBonus_HasUpgradedValue) == 0x000840, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_DamageBonus_TargetStateBonus_HasUpgradedValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_15) == 0x000844, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_16) == 0x000848, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_16' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_DamageBonus_TargetTypeBonus_GearStatEntry) == 0x000850, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_DamageBonus_TargetTypeBonus_GearStatEntry' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_UPGDESC_DamageBonus_TargetTypeBonus_HasUpgradedValue) == 0x0008B8, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_UPGDESC_DamageBonus_TargetTypeBonus_HasUpgradedValue' has a wrong offset!");
static_assert(offsetof(WPN_Revolver_C_GetGearStatEntry, CallFunc_Array_Add_ReturnValue_17) == 0x0008BC, "Member 'WPN_Revolver_C_GetGearStatEntry::CallFunc_Array_Add_ReturnValue_17' has a wrong offset!");

}

