#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HDScopeComponentBase

#include "Basic.hpp"

#include "BP_HDScopeComponentBase_classes.hpp"
#include "BP_HDScopeComponentBase_parameters.hpp"


namespace SDK
{

// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.ExecuteUbergraph_BP_HDScopeComponentBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HDScopeComponentBase_C::ExecuteUbergraph_BP_HDScopeComponentBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "ExecuteUbergraph_BP_HDScopeComponentBase");

	Params::BP_HDScopeComponentBase_C_ExecuteUbergraph_BP_HDScopeComponentBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.UnbindEvents
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_HDPlayerCharacterBase_C*      OldCharacter                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_HDWeaponBase_C*               OldWeapon                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HDScopeComponentBase_C::UnbindEvents(class ABP_HDPlayerCharacterBase_C* OldCharacter, class ABP_HDWeaponBase_C* OldWeapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "UnbindEvents");

	Params::BP_HDScopeComponentBase_C_UnbindEvents Parms{};

	Parms.OldCharacter = OldCharacter;
	Parms.OldWeapon = OldWeapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.BindEvents
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_HDPlayerCharacterBase_C*      NewCharacter                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_HDWeaponBase_C*               NewWeapon                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HDScopeComponentBase_C::BindEvents(class ABP_HDPlayerCharacterBase_C* NewCharacter, class ABP_HDWeaponBase_C* NewWeapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "BindEvents");

	Params::BP_HDScopeComponentBase_C_BindEvents Parms{};

	Parms.NewCharacter = NewCharacter;
	Parms.NewWeapon = NewWeapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.EventDeactivated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UActorComponent*                  Component                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HDScopeComponentBase_C::EventDeactivated(class UActorComponent* Component)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "EventDeactivated");

	Params::BP_HDScopeComponentBase_C_EventDeactivated Parms{};

	Parms.Component = Component;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.EventActivated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UActorComponent*                  Component                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bReset                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_HDScopeComponentBase_C::EventActivated(class UActorComponent* Component, bool bReset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "EventActivated");

	Params::BP_HDScopeComponentBase_C_EventActivated Parms{};

	Parms.Component = Component;
	Parms.bReset = bReset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HDScopeComponentBase_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "ReceiveTick");

	Params::BP_HDScopeComponentBase_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.ChangeSights
// (BlueprintCallable, BlueprintEvent)

void UBP_HDScopeComponentBase_C::ChangeSights()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "ChangeSights");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.ItemChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ADFBaseCharacter*                 Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ADFBaseItem*                      NewEquippedItem                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ADFBaseItem*                      PrevEquippedItem                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HDScopeComponentBase_C::ItemChanged(class ADFBaseCharacter* Character, class ADFBaseItem* NewEquippedItem, class ADFBaseItem* PrevEquippedItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "ItemChanged");

	Params::BP_HDScopeComponentBase_C_ItemChanged Parms{};

	Parms.Character = Character;
	Parms.NewEquippedItem = NewEquippedItem;
	Parms.PrevEquippedItem = PrevEquippedItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.DeathEvent
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            VictimPawn                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AController*                      VictimController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   KillingDamage                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FDamageEvent                     DamageEvent                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class APawn*                            InstigatingPawn                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HDScopeComponentBase_C::DeathEvent(class APawn* VictimPawn, class AController* VictimController, float KillingDamage, const struct FDamageEvent& DamageEvent, class APawn* InstigatingPawn, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "DeathEvent");

	Params::BP_HDScopeComponentBase_C_DeathEvent Parms{};

	Parms.VictimPawn = VictimPawn;
	Parms.VictimController = VictimController;
	Parms.KillingDamage = KillingDamage;
	Parms.DamageEvent = std::move(DamageEvent);
	Parms.InstigatingPawn = InstigatingPawn;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.AimStyle
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHDPlayerCharacter*               Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EHDWeaponAimStyle                       NewAimStyle                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EHDWeaponAimStyle                       PrevAimStyle                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromPlayerInput                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_HDScopeComponentBase_C::AimStyle(class AHDPlayerCharacter* Character, EHDWeaponAimStyle NewAimStyle, EHDWeaponAimStyle PrevAimStyle, bool bFromPlayerInput)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "AimStyle");

	Params::BP_HDScopeComponentBase_C_AimStyle Parms{};

	Parms.Character = Character;
	Parms.NewAimStyle = NewAimStyle;
	Parms.PrevAimStyle = PrevAimStyle;
	Parms.bFromPlayerInput = bFromPlayerInput;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.AimTransition
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsStartTransition                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_HDScopeComponentBase_C::AimTransition(bool bIsStartTransition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "AimTransition");

	Params::BP_HDScopeComponentBase_C_AimTransition Parms{};

	Parms.bIsStartTransition = bIsStartTransition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.AimIn
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_HDScopeComponentBase_C::AimIn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "AimIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.AimOut
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_HDScopeComponentBase_C::AimOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "AimOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.GetData
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ABP_HDPlayerCharacterBase_C*      Character                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AHDPlayerController*              Controller                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UDFCharacterMovementComponent*    Movement                                               (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ADFPlayerCameraManager*           Camera                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_HDWeaponBase_C*               Parent                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USkeletalMeshComponent*           CharacterMesh                                          (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UMeshComponent*                   WeaponMesh                                             (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UBP_HDScopeComponentBase_C*>ParentSightList_0                                      (Parm, OutParm, ContainsInstancedReference, HasGetValueTypeHash)
// TArray<class UMaterialInstanceDynamic*> FirstPersonMatArray                                    (Parm, OutParm, HasGetValueTypeHash)
// TArray<class UMaterialInstanceDynamic*> ThirdPersonMatArray                                    (Parm, OutParm, HasGetValueTypeHash)

void UBP_HDScopeComponentBase_C::GetData(class ABP_HDPlayerCharacterBase_C** Character, class AHDPlayerController** Controller, class UDFCharacterMovementComponent** Movement, class ADFPlayerCameraManager** Camera, class ABP_HDWeaponBase_C** Parent, class USkeletalMeshComponent** CharacterMesh, class UMeshComponent** WeaponMesh, TArray<class UBP_HDScopeComponentBase_C*>* ParentSightList_0, TArray<class UMaterialInstanceDynamic*>* FirstPersonMatArray, TArray<class UMaterialInstanceDynamic*>* ThirdPersonMatArray)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "GetData");

	Params::BP_HDScopeComponentBase_C_GetData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Character != nullptr)
		*Character = Parms.Character;

	if (Controller != nullptr)
		*Controller = Parms.Controller;

	if (Movement != nullptr)
		*Movement = Parms.Movement;

	if (Camera != nullptr)
		*Camera = Parms.Camera;

	if (Parent != nullptr)
		*Parent = Parms.Parent;

	if (CharacterMesh != nullptr)
		*CharacterMesh = Parms.CharacterMesh;

	if (WeaponMesh != nullptr)
		*WeaponMesh = Parms.WeaponMesh;

	if (ParentSightList_0 != nullptr)
		*ParentSightList_0 = std::move(Parms.ParentSightList_0);

	if (FirstPersonMatArray != nullptr)
		*FirstPersonMatArray = std::move(Parms.FirstPersonMatArray);

	if (ThirdPersonMatArray != nullptr)
		*ThirdPersonMatArray = std::move(Parms.ThirdPersonMatArray);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.CanScope
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    CanScope_0                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_HDScopeComponentBase_C::CanScope(bool* CanScope_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "CanScope");

	Params::BP_HDScopeComponentBase_C_CanScope Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CanScope_0 != nullptr)
		*CanScope_0 = Parms.CanScope_0;
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.ScopeEffect
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_HDScopeComponentBase_C::ScopeEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "ScopeEffect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.Init
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_HDScopeComponentBase_C::Init()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "Init");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.SaveDefaults
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_HDScopeComponentBase_C::SaveDefaults()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "SaveDefaults");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.LoadDefaults
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPlayerDead                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_HDScopeComponentBase_C::LoadDefaults(bool IsPlayerDead)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "LoadDefaults");

	Params::BP_HDScopeComponentBase_C_LoadDefaults Parms{};

	Parms.IsPlayerDead = IsPlayerDead;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.SetupOwnerData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsValid                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_HDScopeComponentBase_C::SetupOwnerData(bool* IsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "SetupOwnerData");

	Params::BP_HDScopeComponentBase_C_SetupOwnerData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsValid != nullptr)
		*IsValid = Parms.IsValid;
}


// Function BP_HDScopeComponentBase.BP_HDScopeComponentBase_C.ClearOwnerData
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_HDScopeComponentBase_C::ClearOwnerData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HDScopeComponentBase_C", "ClearOwnerData");

	UObject::ProcessEvent(Func, nullptr);
}

}

