#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HDFactionInfoBase

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "HDMain_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HDFactionInfoBase.BP_HDFactionInfoBase_C
// 0x0770 (0x0850 - 0x00E0)
class UBP_HDFactionInfoBase_C final : public UHDFactionInfo
{
public:
	struct FButtonStyle                           TeamBtnSelectedStyle;                              // 0x00E0(0x0278)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	struct FButtonStyle                           TeamBtnDeselectedStyle;                            // 0x0358(0x0278)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	struct FSlateBrush                            TeamBtnSelectedBrush;                              // 0x05D0(0x0088)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	struct FSlateBrush                            TeamBtnDeselectedBrush;                            // 0x0658(0x0088)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	TSoftObjectPtr<class UTexture2D>              CPFlagIcon;                                        // 0x06E0(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, HasGetValueTypeHash)
	TSoftObjectPtr<class USkeletalMesh>           CharMesh;                                          // 0x0708(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, HasGetValueTypeHash)
	TSoftObjectPtr<class USkeletalMesh>           CharMesh1P;                                        // 0x0730(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, HasGetValueTypeHash)
	class FText                                   TeamBtnDisplayText;                                // 0x0758(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	class FText                                   VictoryText;                                       // 0x0770(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)
	TSoftClassPtr<class UClass>                   RallyPointClass;                                   // 0x0788(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   OutpostClass;                                      // 0x07B0(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, HasGetValueTypeHash)
	TSoftObjectPtr<class UHDKit>                  AIControlledSquadLeaderKit;                        // 0x07D8(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftObjectPtr<class UHDKit>                  AIControlledSquadMemberKit;                        // 0x0800(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftObjectPtr<class UDataTable>              AIVocalProfiles;                                   // 0x0828(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_HDFactionInfoBase_C">();
	}
	static class UBP_HDFactionInfoBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_HDFactionInfoBase_C>();
	}
};
static_assert(alignof(UBP_HDFactionInfoBase_C) == 0x000008, "Wrong alignment on UBP_HDFactionInfoBase_C");
static_assert(sizeof(UBP_HDFactionInfoBase_C) == 0x000850, "Wrong size on UBP_HDFactionInfoBase_C");
static_assert(offsetof(UBP_HDFactionInfoBase_C, TeamBtnSelectedStyle) == 0x0000E0, "Member 'UBP_HDFactionInfoBase_C::TeamBtnSelectedStyle' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, TeamBtnDeselectedStyle) == 0x000358, "Member 'UBP_HDFactionInfoBase_C::TeamBtnDeselectedStyle' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, TeamBtnSelectedBrush) == 0x0005D0, "Member 'UBP_HDFactionInfoBase_C::TeamBtnSelectedBrush' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, TeamBtnDeselectedBrush) == 0x000658, "Member 'UBP_HDFactionInfoBase_C::TeamBtnDeselectedBrush' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, CPFlagIcon) == 0x0006E0, "Member 'UBP_HDFactionInfoBase_C::CPFlagIcon' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, CharMesh) == 0x000708, "Member 'UBP_HDFactionInfoBase_C::CharMesh' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, CharMesh1P) == 0x000730, "Member 'UBP_HDFactionInfoBase_C::CharMesh1P' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, TeamBtnDisplayText) == 0x000758, "Member 'UBP_HDFactionInfoBase_C::TeamBtnDisplayText' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, VictoryText) == 0x000770, "Member 'UBP_HDFactionInfoBase_C::VictoryText' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, RallyPointClass) == 0x000788, "Member 'UBP_HDFactionInfoBase_C::RallyPointClass' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, OutpostClass) == 0x0007B0, "Member 'UBP_HDFactionInfoBase_C::OutpostClass' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, AIControlledSquadLeaderKit) == 0x0007D8, "Member 'UBP_HDFactionInfoBase_C::AIControlledSquadLeaderKit' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, AIControlledSquadMemberKit) == 0x000800, "Member 'UBP_HDFactionInfoBase_C::AIControlledSquadMemberKit' has a wrong offset!");
static_assert(offsetof(UBP_HDFactionInfoBase_C, AIVocalProfiles) == 0x000828, "Member 'UBP_HDFactionInfoBase_C::AIVocalProfiles' has a wrong offset!");

}

