#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DamageArea_ElectroGlobe

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DamageArea_ElectroGlobe.BP_DamageArea_ElectroGlobe_C
// 0x0000 (0x0320 - 0x0320)
class ABP_DamageArea_ElectroGlobe_C final : public ACrabDamageArea
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DamageArea_ElectroGlobe_C">();
	}
	static class ABP_DamageArea_ElectroGlobe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DamageArea_ElectroGlobe_C>();
	}
};
static_assert(alignof(ABP_DamageArea_ElectroGlobe_C) == 0x000008, "Wrong alignment on ABP_DamageArea_ElectroGlobe_C");
static_assert(sizeof(ABP_DamageArea_ElectroGlobe_C) == 0x000320, "Wrong size on ABP_DamageArea_ElectroGlobe_C");

}

