#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AchievementActor

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_AchievementActor.BP_AchievementActor_C.ExecuteUbergraph_BP_AchievementActor
// 0x0100 (0x0100 - 0x0000)
struct BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable;                               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x000C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate1;             // 0x0024(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_WrittenAchievementName;         // 0x0034(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_WrittenProgress;                // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_WrittenUserTag;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)> K2Node_CreateDelegate_OutputDelegate2;             // 0x0044(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_20FC[0x4];                                     // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_WrittenAchievementName1;        // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_WrittenProgress1;               // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_WrittenUserTag1;                // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABFGGameState*                          K2Node_DynamicCast_AsBFGGame_State;                // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_20FD[0x7];                                     // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWorld*                                 CallFunc_GetWorldFromContextObjectSafe_ReturnValue; // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBFGAchievementManager*                 CallFunc_GetAchievementManager_ReturnValue;        // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue1;                // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABFGGameState*                          K2Node_DynamicCast_AsBFGGame_State1;               // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess1;                      // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_20FE[0x3];                                     // 0x00A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)> K2Node_CreateDelegate_OutputDelegate3;             // 0x00A4(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_20FF[0x4];                                     // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWorld*                                 CallFunc_GetWorldFromContextObjectSafe_ReturnValue1; // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBFGAchievementManager*                 CallFunc_GetAchievementManager_ReturnValue1;       // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_Event__pPlayerController;                   // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_Event__nAchievementID;                      // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event__fAchievementProgress;                // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event__bShouldSaved;                        // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2100[0x3];                                     // 0x00DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UAchievementQueryCallbackProxy*         CallFunc_CacheAchievements_ReturnValue;            // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWorld*                                 CallFunc_GetWorldFromContextObjectSafe_ReturnValue2; // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAchievementWriteCallbackProxy*         CallFunc_WriteAchievementProgress_ReturnValue;     // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue1;                     // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor) == 0x000008, "Wrong alignment on BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor");
static_assert(sizeof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor) == 0x000100, "Wrong size on BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, EntryPoint) == 0x000000, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, Temp_int_Variable) == 0x000004, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, Temp_float_Variable) == 0x000008, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, Temp_name_Variable) == 0x00000C, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_CreateDelegate_OutputDelegate) == 0x000014, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_CreateDelegate_OutputDelegate1) == 0x000024, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_CreateDelegate_OutputDelegate1' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_CustomEvent_WrittenAchievementName) == 0x000034, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_CustomEvent_WrittenAchievementName' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_CustomEvent_WrittenProgress) == 0x00003C, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_CustomEvent_WrittenProgress' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_CustomEvent_WrittenUserTag) == 0x000040, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_CustomEvent_WrittenUserTag' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_CreateDelegate_OutputDelegate2) == 0x000044, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_CreateDelegate_OutputDelegate2' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_GetGameState_ReturnValue) == 0x000058, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_CustomEvent_WrittenAchievementName1) == 0x000060, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_CustomEvent_WrittenAchievementName1' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_CustomEvent_WrittenProgress1) == 0x000068, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_CustomEvent_WrittenProgress1' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_CustomEvent_WrittenUserTag1) == 0x00006C, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_CustomEvent_WrittenUserTag1' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_DynamicCast_AsBFGGame_State) == 0x000070, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_DynamicCast_AsBFGGame_State' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_DynamicCast_bSuccess) == 0x000078, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_GetWorldFromContextObjectSafe_ReturnValue) == 0x000080, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_GetWorldFromContextObjectSafe_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_GetAchievementManager_ReturnValue) == 0x000088, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_GetAchievementManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_GetGameState_ReturnValue1) == 0x000090, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_GetGameState_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_DynamicCast_AsBFGGame_State1) == 0x000098, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_DynamicCast_AsBFGGame_State1' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_DynamicCast_bSuccess1) == 0x0000A0, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_DynamicCast_bSuccess1' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_CreateDelegate_OutputDelegate3) == 0x0000A4, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_CreateDelegate_OutputDelegate3' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_GetWorldFromContextObjectSafe_ReturnValue1) == 0x0000B8, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_GetWorldFromContextObjectSafe_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_GetAchievementManager_ReturnValue1) == 0x0000C0, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_GetAchievementManager_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_Event__pPlayerController) == 0x0000C8, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_Event__pPlayerController' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_Event__nAchievementID) == 0x0000D0, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_Event__nAchievementID' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_Event__fAchievementProgress) == 0x0000D8, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_Event__fAchievementProgress' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, K2Node_Event__bShouldSaved) == 0x0000DC, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::K2Node_Event__bShouldSaved' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_CacheAchievements_ReturnValue) == 0x0000E0, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_CacheAchievements_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_GetWorldFromContextObjectSafe_ReturnValue2) == 0x0000E8, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_GetWorldFromContextObjectSafe_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_WriteAchievementProgress_ReturnValue) == 0x0000F0, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_WriteAchievementProgress_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_IsValid_ReturnValue) == 0x0000F8, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor, CallFunc_IsValid_ReturnValue1) == 0x0000F9, "Member 'BP_AchievementActor_C_ExecuteUbergraph_BP_AchievementActor::CallFunc_IsValid_ReturnValue1' has a wrong offset!");

// Function BP_AchievementActor.BP_AchievementActor_C.OnAchievementAwarded
// 0x0018 (0x0018 - 0x0000)
struct BP_AchievementActor_C_OnAchievementAwarded final
{
public:
	class APlayerController*                      _pPlayerController;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   _nAchievementID;                                   // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         _fAchievementProgress;                             // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          _bShouldSaved;                                     // 0x0014(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AchievementActor_C_OnAchievementAwarded) == 0x000008, "Wrong alignment on BP_AchievementActor_C_OnAchievementAwarded");
static_assert(sizeof(BP_AchievementActor_C_OnAchievementAwarded) == 0x000018, "Wrong size on BP_AchievementActor_C_OnAchievementAwarded");
static_assert(offsetof(BP_AchievementActor_C_OnAchievementAwarded, _pPlayerController) == 0x000000, "Member 'BP_AchievementActor_C_OnAchievementAwarded::_pPlayerController' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_OnAchievementAwarded, _nAchievementID) == 0x000008, "Member 'BP_AchievementActor_C_OnAchievementAwarded::_nAchievementID' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_OnAchievementAwarded, _fAchievementProgress) == 0x000010, "Member 'BP_AchievementActor_C_OnAchievementAwarded::_fAchievementProgress' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_OnAchievementAwarded, _bShouldSaved) == 0x000014, "Member 'BP_AchievementActor_C_OnAchievementAwarded::_bShouldSaved' has a wrong offset!");

// Function BP_AchievementActor.BP_AchievementActor_C.OnSuccess_EF677678481A3E3701207FABE7206004
// 0x0010 (0x0010 - 0x0000)
struct BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004 final
{
public:
	class FName                                   WrittenAchievementName;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WrittenProgress;                                   // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         WrittenUserTag;                                    // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004) == 0x000004, "Wrong alignment on BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004");
static_assert(sizeof(BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004) == 0x000010, "Wrong size on BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004");
static_assert(offsetof(BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004, WrittenAchievementName) == 0x000000, "Member 'BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004::WrittenAchievementName' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004, WrittenProgress) == 0x000008, "Member 'BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004::WrittenProgress' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004, WrittenUserTag) == 0x00000C, "Member 'BP_AchievementActor_C_OnSuccess_EF677678481A3E3701207FABE7206004::WrittenUserTag' has a wrong offset!");

// Function BP_AchievementActor.BP_AchievementActor_C.OnFailure_EF677678481A3E3701207FABE7206004
// 0x0010 (0x0010 - 0x0000)
struct BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004 final
{
public:
	class FName                                   WrittenAchievementName;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WrittenProgress;                                   // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         WrittenUserTag;                                    // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004) == 0x000004, "Wrong alignment on BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004");
static_assert(sizeof(BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004) == 0x000010, "Wrong size on BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004");
static_assert(offsetof(BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004, WrittenAchievementName) == 0x000000, "Member 'BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004::WrittenAchievementName' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004, WrittenProgress) == 0x000008, "Member 'BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004::WrittenProgress' has a wrong offset!");
static_assert(offsetof(BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004, WrittenUserTag) == 0x00000C, "Member 'BP_AchievementActor_C_OnFailure_EF677678481A3E3701207FABE7206004::WrittenUserTag' has a wrong offset!");

}

