#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Struct_Skylight_params

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// ScriptStruct BP_Struct_Skylight_params.BP_Struct_Skylight_params
// 0x0008 (0x0008 - 0x0000)
struct FBP_Struct_Skylight_params final
{
public:
	float                                         Skylight_intensity_7_F173A7FF41A1B13C803013B656A1AD3D; // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 Skylight_lightColor_4_511E8E8C4CC67A6DDC03F1AAA1D27379; // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FBP_Struct_Skylight_params) == 0x000004, "Wrong alignment on FBP_Struct_Skylight_params");
static_assert(sizeof(FBP_Struct_Skylight_params) == 0x000008, "Wrong size on FBP_Struct_Skylight_params");
static_assert(offsetof(FBP_Struct_Skylight_params, Skylight_intensity_7_F173A7FF41A1B13C803013B656A1AD3D) == 0x000000, "Member 'FBP_Struct_Skylight_params::Skylight_intensity_7_F173A7FF41A1B13C803013B656A1AD3D' has a wrong offset!");
static_assert(offsetof(FBP_Struct_Skylight_params, Skylight_lightColor_4_511E8E8C4CC67A6DDC03F1AAA1D27379) == 0x000004, "Member 'FBP_Struct_Skylight_params::Skylight_lightColor_4_511E8E8C4CC67A6DDC03F1AAA1D27379' has a wrong offset!");

}

