#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ControlsWidget

#include "Basic.hpp"

#include "ControlsWidget_classes.hpp"
#include "ControlsWidget_parameters.hpp"


namespace SDK
{

// Function ControlsWidget.ControlsWidget_C.BndEvt__ControlsWidget_Button_0_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UControlsWidget_C::BndEvt__ControlsWidget_Button_0_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ControlsWidget_C", "BndEvt__ControlsWidget_Button_0_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ControlsWidget.ControlsWidget_C.BndEvt__ControlsWidget_Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UControlsWidget_C::BndEvt__ControlsWidget_Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ControlsWidget_C", "BndEvt__ControlsWidget_Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ControlsWidget.ControlsWidget_C.ExecuteUbergraph_ControlsWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UControlsWidget_C::ExecuteUbergraph_ControlsWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ControlsWidget_C", "ExecuteUbergraph_ControlsWidget");

	Params::ControlsWidget_C_ExecuteUbergraph_ControlsWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ControlsWidget.ControlsWidget_C.HideControls
// (Public, BlueprintCallable, BlueprintEvent)

void UControlsWidget_C::HideControls()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ControlsWidget_C", "HideControls");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ControlsWidget.ControlsWidget_C.ShowControls
// (Public, BlueprintCallable, BlueprintEvent)

void UControlsWidget_C::ShowControls()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ControlsWidget_C", "ShowControls");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ControlsWidget.ControlsWidget_C.TranslateText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ALanguageManager_C*               LanguageMan                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UControlsWidget_C::TranslateText(class ALanguageManager_C* LanguageMan)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ControlsWidget_C", "TranslateText");

	Params::ControlsWidget_C_TranslateText Parms{};

	Parms.LanguageMan = LanguageMan;

	UObject::ProcessEvent(Func, &Parms);
}

}

