#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Nurse_PostAnimBP

#include "Basic.hpp"

#include "Nurse_PostAnimBP_classes.hpp"
#include "Nurse_PostAnimBP_parameters.hpp"


namespace SDK
{

// Function Nurse_PostAnimBP.Nurse_PostAnimBP_C.ExecuteUbergraph_Nurse_PostAnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNurse_PostAnimBP_C::ExecuteUbergraph_Nurse_PostAnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Nurse_PostAnimBP_C", "ExecuteUbergraph_Nurse_PostAnimBP");

	Params::Nurse_PostAnimBP_C_ExecuteUbergraph_Nurse_PostAnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Nurse_PostAnimBP.Nurse_PostAnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNurse_PostAnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Nurse_PostAnimBP_C", "BlueprintUpdateAnimation");

	Params::Nurse_PostAnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Nurse_PostAnimBP.Nurse_PostAnimBP_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UNurse_PostAnimBP_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Nurse_PostAnimBP_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}

}

